import { Platform, StyleSheet } from "react-native";
import { colorTokens, fonts } from "@/theme";

export const styles = StyleSheet.create({
  pressed: { opacity: 0.85 },
  outerContainer: {
    width: "100%",
    flex: 1,
    flexDirection: "row",
    backgroundColor: "#F8FAF9",
  },
  sidebar: {
    width: 256,
    backgroundColor: "#FFFFFF",
    borderRightWidth: 0.8,
    borderRightColor: "rgba(11,26,23,0.08)",
    paddingVertical: 20,
    paddingHorizontal: 16,
  },
  sidebarHeader: {
    gap: 16,
    marginBottom: 16,
    paddingHorizontal: 8,
  },
  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  brandIconBg: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#04cf92",
    alignItems: "center",
    justifyContent: "center",
  },
  brandText: {
    fontSize: 18,
    fontFamily: fonts.extraBold,
    color: "#0B1A17",
  },
  brandTextAccent: {
    color: "#04cf92",
  },
  sellerRolePill: {
    backgroundColor: "#E8EEFC",
    borderRadius: 999,
    paddingVertical: 4,
    paddingHorizontal: 12,
    alignItems: "center",
  },
  sellerRoleText: {
    color: "#2251D6",
    fontSize: 12,
    fontFamily: fonts.semiBold,
  },
  sidebarNavScroll: {
    gap: 2,
    paddingVertical: 8,
  },
  navItem: {
    minHeight: 42,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
  },
  navItemActive: {
    backgroundColor: "#E6FAF4",
  },
  navItemDanger: {
    marginTop: 8,
  },
  navItemText: {
    flex: 1,
    fontSize: 14,
    fontFamily: fonts.semiBold,
    color: "#5C6B66",
  },
  navItemTextActive: {
    color: "#04cf92",
    fontFamily: fonts.bold,
  },
  navItemTextDanger: {
    color: "#D4183D",
  },
  badgeCountPill: {
    backgroundColor: "#F4823A",
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  badgeCountText: {
    color: colorTokens.onAccent,
    fontSize: 12,
    fontFamily: fonts.bold,
  },
  mainContent: {
    flex: 1,
    minWidth: 0,
    flexDirection: "column",
    zIndex: 10,
  },
  topHeader: {
    minHeight: 64,
    backgroundColor: "rgba(255,255,255,0.92)",
    borderBottomWidth: 0.8,
    borderBottomColor: "rgba(11,26,23,0.08)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 24,
    paddingVertical: 12,
    zIndex: 1000,
  },
  headerTitle: {
    fontSize: 19,
    fontFamily: fonts.extraBold,
    color: "#0B1A17",
    letterSpacing: -0.38,
  },
  headerSubtitle: {
    fontSize: 12,
    fontFamily: fonts.regular,
    color: "#5C6B66",
    marginTop: 2,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  searchContainer: {
    width: 256,
    height: 38,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#F4F6F5",
    borderRadius: 999,
    borderWidth: 0.8,
    borderColor: "rgba(11,26,23,0.08)",
    paddingHorizontal: 13,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    fontFamily: fonts.regular,
    color: "#0B1A17",
  },
  iconCircleBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 0.8,
    borderColor: "rgba(11,26,23,0.08)",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    backgroundColor: "#FFFFFF",
  },
  iconCircleBtnActive: {
    borderColor: "#04cf92",
    backgroundColor: "#E6FAF4",
  },
  iconCircleBtnPressed: {
    transform: [{ scale: 0.96 }],
    backgroundColor: "rgba(11,26,23,0.04)",
  },
  notificationWrap: {
    position: "relative",
    zIndex: 10000,
  },
  notificationBadgePill: {
    position: "absolute",
    top: -4,
    right: -4,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: "#F4823A",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
    borderWidth: 1.5,
    borderColor: "#FFFFFF",
  },
  notificationBadgeText: {
    fontSize: 10,
    fontFamily: fonts.bold,
    color: colorTokens.onAccent,
    lineHeight: 12,
  },
  notificationDropdown: {
    position: "absolute",
    top: 48,
    right: 0,
    width: 360,
    maxHeight: 460,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(11,26,23,0.08)",
    shadowColor: "#0B1A17",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.12,
    shadowRadius: 28,
    elevation: 8,
    zIndex: 999,
    overflow: "hidden",
  },
  dropdownHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(11,26,23,0.06)",
    backgroundColor: "#FAFBFB",
  },
  dropdownHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  dropdownTitle: {
    fontSize: 15,
    fontFamily: fonts.bold,
    color: "#0B1A17",
  },
  unreadCountPill: {
    backgroundColor: "#E6FAF4",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
  },
  unreadCountPillText: {
    fontSize: 11,
    fontFamily: fonts.bold,
    color: "#04cf92",
  },
  markAllReadBtn: {
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 6,
  },
  markAllReadText: {
    fontSize: 12,
    fontFamily: fonts.semiBold,
    color: "#04cf92",
  },
  dropdownScroll: {
    maxHeight: 320,
  },
  dropdownScrollContent: {
    padding: 12,
    gap: 8,
  },
  dropdownEmpty: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 36,
    gap: 10,
  },
  dropdownEmptyText: {
    fontSize: 13,
    fontFamily: fonts.regular,
    color: "rgba(11,26,23,0.5)",
  },
  dropdownFooter: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: "rgba(11,26,23,0.06)",
    backgroundColor: "#FAFBFB",
    alignItems: "center",
  },
  viewAllNotificationsBtn: {
    paddingVertical: 4,
  },
  viewAllNotificationsText: {
    fontSize: 13,
    fontFamily: fonts.semiBold,
    color: "#04cf92",
  },
  headerDotIndicator: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#F4823A",
  },
  viewSiteBtn: {
    height: 38,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 0.8,
    borderColor: "rgba(11,26,23,0.08)",
    borderRadius: 999,
    paddingHorizontal: 14,
    backgroundColor: "#FFFFFF",
  },
  viewSiteText: {
    fontSize: 14,
    fontFamily: fonts.semiBold,
    color: "#0B1A17",
  },
  workspaceScroll: {
    flexGrow: 1,
    justifyContent: "space-between",
  },
  scrollBody: {
    padding: 24,
    gap: 20,
  },
  scrollBodyPhone: {
    padding: 12,
    gap: 16,
  },
  scrollBodyNarrow: {
    paddingHorizontal: 8,
    paddingVertical: 10,
  },
  stepperContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
  },
  stepperRow: {
    flexDirection: "row",
    alignItems: "center",
    maxWidth: 600,
    width: "100%",
  },
  stepItemWrap: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
  },
  stepCircleWrap: {
    alignItems: "center",
    gap: 6,
  },
  stepCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F4F6F5",
    borderWidth: 1.5,
    borderColor: "rgba(11,26,23,0.15)",
    alignItems: "center",
    justifyContent: "center",
  },
  stepCircleCurrent: {
    borderColor: "#04cf92",
    backgroundColor: "#FFFFFF",
  },
  stepCircleDone: {
    backgroundColor: "#04cf92",
    borderColor: "#04cf92",
  },
  stepCircleText: {
    fontSize: 14,
    fontFamily: fonts.bold,
    color: "#5C6B66",
  },
  stepCircleTextCurrent: {
    color: "#04cf92",
  },
  stepLabelText: {
    fontSize: 12,
    fontFamily: fonts.regular,
    color: "#5C6B66",
  },
  stepLabelTextActive: {
    fontFamily: fonts.bold,
    color: "#0B1A17",
  },
  stepConnectorLine: {
    flex: 1,
    height: 2,
    backgroundColor: "rgba(11,26,23,0.12)",
    marginHorizontal: 8,
    marginBottom: 20,
  },
  stepConnectorLineDone: {
    backgroundColor: "#04cf92",
  },
  stepCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(11,26,23,0.11)",
    shadowColor: "#0B1A17",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 16,
    elevation: 2,
    padding: 32,
    gap: 24,
  },
  stepCardPhone: {
    padding: 16,
    borderRadius: 18,
    gap: 16,
  },
  stepCardNarrow: {
    paddingHorizontal: 10,
    paddingVertical: 14,
    borderRadius: 14,
  },
  errorBanner: {
    backgroundColor: "#FDEBEC",
    borderColor: "#F4B9C1",
    borderRadius: 12,
    borderWidth: 1,
    padding: 12,
  },
  errorBannerText: { color: "#A50F2D", fontFamily: fonts.semiBold, fontSize: 13 },
  stepFormBody: {
    gap: 20,
  },
  formGroup: {
    gap: 8,
  },
  formLabel: {
    fontSize: 14,
    fontFamily: fonts.bold,
    color: "#0B1A17",
  },
  formLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  formHelperCharCount: {
    fontSize: 12,
    fontFamily: fonts.regular,
    color: "#899790",
  },
  formInput: {
    height: 48,
    borderRadius: 16,
    backgroundColor: "#F4F6F5",
    borderWidth: 1.2,
    borderColor: "rgba(11,26,23,0.12)",
    paddingHorizontal: 16,
    fontSize: 14,
    fontFamily: fonts.regular,
    color: "#0B1A17",
  },
  formTextarea: {
    minHeight: 116,
    borderRadius: 16,
    backgroundColor: "#F4F6F5",
    borderWidth: 1.2,
    borderColor: "rgba(11,26,23,0.12)",
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 14,
    fontSize: 14,
    fontFamily: fonts.regular,
    color: "#0B1A17",
    textAlignVertical: "top",
    lineHeight: 22,
  },
  formTextareaFocused: {
    borderColor: "#00C885",
    backgroundColor: "#FFFFFF",
    shadowColor: "#00C885",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 2,
  },
  areaPickerButton: { alignItems: "center", flexDirection: "row", gap: 10 },
  areaPickerText: { color: "#0B1A17", flex: 1, fontFamily: fonts.regular, fontSize: 14 },
  areaPickerPlaceholder: { color: "#899790" },
  formRow: {
    flexDirection: "row",
    gap: 16,
  },
  formRowPhone: {
    flexDirection: "column",
  },
  toggleRow: {
    flexDirection: "row",
    height: 48,
    backgroundColor: "#F4F6F5",
    borderRadius: 16,
    borderWidth: 1.2,
    borderColor: "rgba(11,26,23,0.12)",
    padding: 4,
  },
  toggleBtn: {
    flex: 1,
    minWidth: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
  },
  toggleBtnActive: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(11,26,23,0.08)",
    shadowColor: "rgba(11,26,23,0.06)",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 1,
    shadowRadius: 3,
    elevation: 1,
  },
  toggleBtnText: {
    fontSize: 14,
    fontFamily: fonts.semiBold,
    color: "#5C6B66",
  },
  toggleBtnTextActive: {
    color: "#04cf92",
  },
  toggleGridMobile: {
    flexDirection: "row",
    flexWrap: "wrap",
    backgroundColor: "#F4F6F5",
    borderRadius: 16,
    borderWidth: 1.2,
    borderColor: "rgba(11,26,23,0.12)",
    padding: 4,
    gap: 6,
  },
  toggleGridBtnMobile: {
    width: "48.5%",
    flexGrow: 1,
    minWidth: 0,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
  },
  amenitiesWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  amenityPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    height: 38,
    paddingHorizontal: 16,
    borderRadius: 999,
    backgroundColor: "#FFFFFF",
    borderWidth: 0.8,
    borderColor: "rgba(11,26,23,0.12)",
  },
  amenityPillSelected: {
    borderColor: "#04cf92",
    backgroundColor: "#E6FAF4",
  },
  amenityPillText: {
    fontSize: 14,
    fontFamily: fonts.regular,
    color: "#0B1A17",
  },
  amenityPillTextSelected: {
    fontFamily: fonts.semiBold,
    color: "#04cf92",
  },
  categoryGrid: {
    flexDirection: "row",
    gap: 12,
  },
  categoryGridMobile: {
    flexDirection: "column",
  },
  categoryCard: {
    flex: 1,
    padding: 16,
    borderRadius: 16,
    backgroundColor: "#F8FAF9",
    borderWidth: 1.5,
    borderColor: "rgba(11, 26, 23, 0.08)",
    gap: 6,
    ...(Platform.select({
      web: {
        transition: "all 0.18s ease-in-out",
        cursor: "pointer",
      },
      default: {},
    }) as any),
  },
  categoryCardSelected: {
    borderColor: "#04cf92",
    backgroundColor: "#E6FAF4",
    ...(Platform.select({
      web: {
        boxShadow: "0 2px 10px rgba(4, 207, 146, 0.18)",
      },
      default: {},
    }) as any),
  },
  categoryIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },
  categoryIconWrapSelected: {
    backgroundColor: "rgba(4, 207, 146, 0.15)",
  },
  categoryLabel: {
    fontSize: 15,
    fontFamily: fonts.bold,
    color: "#0B1A17",
  },
  categoryLabelSelected: {
    color: "#04cf92",
  },
  categoryDesc: {
    fontSize: 12,
    fontFamily: fonts.regular,
    color: "#5C6B66",
    lineHeight: 16,
  },
  categoryDescSelected: {
    color: "#0B1A17",
  },
  subtypeWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  subtypePill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "rgba(11, 26, 23, 0.12)",
  },
  subtypePillSelected: {
    borderColor: "#04cf92",
    backgroundColor: "#E6FAF4",
  },
  subtypePillText: {
    fontSize: 13,
    fontFamily: fonts.medium,
    color: "#5C6B66",
  },
  subtypePillTextSelected: {
    fontFamily: fonts.semiBold,
    color: "#04cf92",
  },
  customSubtypeGroup: {
    gap: 6,
    marginTop: 4,
  },
  unitSelectorRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#F4F6F5",
    padding: 3,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(11, 26, 23, 0.08)",
  },
  unitPill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 7,
  },
  unitPillActive: {
    backgroundColor: "#04cf92",
  },
  unitPillText: {
    fontSize: 11,
    fontFamily: fonts.semiBold,
    color: "#5C6B66",
    textTransform: "uppercase",
  },
  unitPillTextActive: {
    color: colorTokens.onBrand,
  },
  formHint: {
    fontSize: 12,
    fontFamily: fonts.regular,
    color: "#5C6B66",
  },
  formHelperText: {
    fontSize: 12,
    fontFamily: fonts.regular,
    color: "#5C6B66",
    marginTop: 2,
  },
  mapContainer: {
    height: 320,
    borderRadius: 16,
    overflow: "hidden",
    position: "relative",
  },
  mapImage: {
    width: "100%",
    height: "100%",
  },
  mapOverlayCenter: {
    position: "absolute",
    top: "35%",
    left: "40%",
    alignItems: "center",
    gap: 6,
  },
  mapTooltip: {
    backgroundColor: "#0B1A17",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  mapTooltipText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontFamily: fonts.semiBold,
  },
  mapPinCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#04cf92",
    alignItems: "center",
    justifyContent: "center",
    elevation: 4,
  },
  mapCoordPill: {
    position: "absolute",
    bottom: 12,
    left: 12,
    backgroundColor: "rgba(255,255,255,0.92)",
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  mapCoordText: {
    fontSize: 12,
    fontFamily: fonts.regular,
    color: "#0B1A17",
  },
  mediaGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
  },
  mediaCard: {
    width: 140,
    height: 140,
    borderRadius: 16,
    overflow: "hidden",
    position: "relative",
  },
  mediaImg: {
    width: "100%",
    height: "100%",
  },
  coverBadge: {
    position: "absolute",
    bottom: 8,
    left: 8,
    backgroundColor: "#04cf92",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 2,
  },
  coverBadgeText: {
    color: colorTokens.onBrand,
    fontSize: 11,
    fontFamily: fonts.bold,
  },
  removeMediaButton: {
    alignItems: "center",
    backgroundColor: "rgba(11,26,23,0.82)",
    borderRadius: 16,
    height: 30,
    justifyContent: "center",
    position: "absolute",
    right: 8,
    top: 8,
    width: 30,
  },
  addMediaCard: {
    width: 140,
    height: 140,
    borderRadius: 16,
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: "rgba(11,26,23,0.2)",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: "#FAFBFB",
  },
  addMediaText: {
    fontSize: 14,
    fontFamily: fonts.semiBold,
    color: "#5C6B66",
  },
  videoDropzone: {
    height: 100,
    borderRadius: 16,
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: "rgba(11,26,23,0.2)",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#FAFBFB",
  },
  videoDropzoneText: {
    fontSize: 14,
    fontFamily: fonts.regular,
    color: "#5C6B66",
  },
  uploadHint: { color: "#6B7D78", fontFamily: fonts.regular, fontSize: 12, marginTop: 8 },
  uploadedVideoRow: {
    alignItems: "center",
    backgroundColor: "#E6FAF4",
    borderRadius: 10,
    flexDirection: "row",
    gap: 10,
    marginBottom: 8,
    padding: 12,
  },
  uploadedVideoText: { color: "#0B1A17", flex: 1, fontFamily: fonts.regular, fontSize: 13 },
  readyAlertBanner: {
    backgroundColor: "#E6FAF4",
    borderRadius: 16,
    padding: 18,
    gap: 6,
  },
  readyAlertTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  readyAlertTitle: {
    fontSize: 15,
    fontFamily: fonts.bold,
    color: "#04cf92",
  },
  readyAlertDesc: {
    fontSize: 14,
    fontFamily: fonts.regular,
    color: "#5C6B66",
  },
  reviewGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  reviewCard: {
    width: "48%",
    backgroundColor: "#F4F6F5",
    borderRadius: 16,
    borderWidth: 1.2,
    borderColor: "rgba(11,26,23,0.12)",
    padding: 14,
    gap: 4,
  },
  reviewCardLabel: {
    fontSize: 12,
    fontFamily: fonts.regular,
    color: "#5C6B66",
  },
  reviewCardValue: {
    fontSize: 14,
    fontFamily: fonts.bold,
    color: "#0B1A17",
  },
  wizardActionBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 16,
    borderTopWidth: 0.8,
    borderTopColor: "rgba(11,26,23,0.08)",
  },
  backBtn: {
    height: 40,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    borderWidth: 0.8,
    borderColor: "rgba(11,26,23,0.12)",
    paddingHorizontal: 18,
  },
  backBtnText: {
    fontSize: 14,
    fontFamily: fonts.semiBold,
    color: "#0B1A17",
  },
  wizardRightActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  saveDraftBtn: {
    height: 40,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderRadius: 999,
    borderWidth: 0.8,
    borderColor: "rgba(11,26,23,0.12)",
    paddingHorizontal: 18,
  },
  saveDraftText: {
    fontSize: 14,
    fontFamily: fonts.semiBold,
    color: "#0B1A17",
  },
  nextBtn: {
    height: 40,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#04cf92",
    borderRadius: 999,
    paddingHorizontal: 22,
  },
  nextBtnText: {
    color: colorTokens.onBrand,
    fontSize: 14,
    fontFamily: fonts.semiBold,
  },
  publishBtn: {
    height: 40,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#04cf92",
    borderRadius: 999,
    paddingHorizontal: 22,
  },
  publishBtnText: {
    color: colorTokens.onBrand,
    fontSize: 14,
    fontFamily: fonts.semiBold,
  },
  wizardActionBarMobile: {
    paddingTop: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 6,
    borderTopWidth: 1.5,
    borderTopColor: "rgba(11,26,23,0.1)",
  },
  wizardRightActionsMobile: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  wizardRightActionsNarrow: {
    gap: 5,
  },
  backBtnMobile: {
    height: 38,
    paddingHorizontal: 12,
    gap: 4,
    borderRadius: 999,
    borderWidth: 0.8,
    borderColor: "rgba(11,26,23,0.12)",
    backgroundColor: "#FFFFFF",
  },
  backBtnNarrow: {
    paddingHorizontal: 9,
    height: 36,
  },
  backBtnTextMobile: {
    fontSize: 13,
    fontFamily: fonts.semiBold,
    color: "#5C6B66",
  },
  saveDraftBtnMobile: {
    height: 38,
    paddingHorizontal: 11,
    gap: 4,
    borderRadius: 999,
    borderWidth: 0.8,
    borderColor: "rgba(11,26,23,0.12)",
    backgroundColor: "#FFFFFF",
  },
  saveDraftBtnNarrow: {
    paddingHorizontal: 8,
    height: 36,
  },
  saveDraftTextMobile: {
    fontSize: 13,
    fontFamily: fonts.semiBold,
    color: "#0B1A17",
  },
  nextBtnMobile: {
    height: 38,
    paddingHorizontal: 14,
    gap: 4,
    borderRadius: 999,
    backgroundColor: "#04cf92",
  },
  nextBtnNarrow: {
    paddingHorizontal: 10,
    height: 36,
  },
  nextBtnTextMobile: {
    fontSize: 13,
    fontFamily: fonts.semiBold,
    color: colorTokens.onBrand,
  },
  publishBtnMobile: {
    height: 38,
    paddingHorizontal: 14,
    gap: 4,
    borderRadius: 999,
  },
  publishBtnNarrow: {
    paddingHorizontal: 10,
    height: 36,
  },
  publishBtnTextMobile: {
    fontSize: 13,
    fontFamily: fonts.semiBold,
    color: colorTokens.onBrand,
  },
  btnTextNarrow: {
    fontSize: 12,
  },
});
