import { Platform, StyleSheet } from "react-native";
import { colorTokens, fonts, shadow } from "@/theme";

export const styles = StyleSheet.create({
  pressed: { opacity: 0.85 },
  requestState: {
    flex: 1,
    minHeight: 420,
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
    padding: 24,
  },
  requestError: {
    color: "#4F625D",
    fontFamily: fonts.regular,
    fontSize: 15,
    textAlign: "center",
  },
  retryButton: {
    alignItems: "center",
    backgroundColor: "#04cf92",
    borderRadius: 10,
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 18,
    paddingVertical: 11,
  },
  retryText: { color: colorTokens.onBrand, fontFamily: fonts.semiBold, fontSize: 14 },
  scrollBody: {
    padding: 24,
    gap: 20,
  },
  scrollBodyPhone: {
    padding: 16,
    gap: 16,
  },
  topHeaderNav: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  backLink: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    height: 38,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: "#FFFFFF",
    borderWidth: 0.8,
    borderColor: "rgba(11,26,23,0.08)",
  },
  backLinkText: {
    fontSize: 14,
    fontFamily: fonts.semiBold,
    color: "#0B1A17",
  },
  actionHeaderBtns: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  actionCircleBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#FFFFFF",
    borderWidth: 0.8,
    borderColor: "rgba(11,26,23,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  mainLayoutGrid: {
    flexDirection: "row",
    gap: 24,
  },
  mainLayoutGridTablet: {
    flexDirection: "column",
  },
  leftColumn: {
    flex: 1.8,
    gap: 20,
  },
  rightColumn: {
    flex: 1,
    gap: 20,
  },
  galleryContainer: {
    gap: 12,
  },
  mainImageWrap: {
    width: "100%",
    height: 380,
    borderRadius: 24,
    overflow: "hidden",
    position: "relative",
    backgroundColor: "#F4F6F5",
  },
  mainImage: {
    width: "100%",
    height: "100%",
  },
  mediaPlaceholder: {
    alignItems: "center",
    height: "100%",
    justifyContent: "center",
    gap: 10,
    width: "100%",
  },
  mediaPlaceholderText: { color: "#6B7D78", fontFamily: fonts.regular, fontSize: 14 },
  similarThumbPlaceholder: { alignItems: "center", backgroundColor: "#E8EEEC", justifyContent: "center" },
  galleryBadgesRow: {
    position: "absolute",
    top: 16,
    left: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  verifiedTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#FFFFFF",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 5,
  },
  verifiedTagText: {
    fontSize: 12,
    fontFamily: fonts.semiBold,
    color: "#04cf92",
  },
  forRentTag: {
    backgroundColor: "#E8EEFC",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 5,
  },
  forRentTagText: {
    fontSize: 12,
    fontFamily: fonts.semiBold,
    color: "#2251D6",
  },
  thumbnailsRow: {
    flexDirection: "row",
    gap: 12,
  },
  mainImageWrapPhone: {
    height: 260,
    borderRadius: 18,
  },
  thumbnailsContainer: {
    position: "relative",
    width: "100%",
    justifyContent: "center",
  },
  thumbnailsScrollContent: {
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
    paddingVertical: 4,
    paddingHorizontal: 2,
  },
  thumbnailCard: {
    width: 100,
    height: 70,
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 2,
    borderColor: "transparent",
    position: "relative",
    backgroundColor: "#E8EEEC",
  },
  thumbnailCardPhone: {
    width: 82,
    height: 58,
    borderRadius: 10,
  },
  thumbnailCardActive: {
    borderColor: "#04cf92",
    opacity: 1,
  },
  thumbnailCardInactive: {
    opacity: 0.72,
  },
  thumbnailImg: {
    width: "100%",
    height: "100%",
  },
  moreImagesOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(11, 26, 23, 0.78)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 4,
    borderRadius: 10,
  },
  moreImagesText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontFamily: fonts.bold,
    textAlign: "center",
    letterSpacing: -0.2,
  },
  thumbScrollBtn: {
    position: "absolute",
    zIndex: 10,
    top: "50%",
    marginTop: -16,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(11, 26, 23, 0.8)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
    ...shadow,
  },
  thumbScrollBtnLeft: {
    left: 4,
  },
  thumbScrollBtnRight: {
    right: 4,
  },
  heroNavBtn: {
    position: "absolute",
    zIndex: 10,
    top: "50%",
    marginTop: -22,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(11, 26, 23, 0.65)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.25)",
    ...shadow,
  },
  heroNavBtnLeft: {
    left: 16,
  },
  heroNavBtnRight: {
    right: 16,
  },
  photoCountPill: {
    position: "absolute",
    bottom: 16,
    right: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(11, 26, 23, 0.75)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.15)",
  },
  photoCountText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontFamily: fonts.semiBold,
  },
  lightboxBackdrop: {
    flex: 1,
    backgroundColor: "rgba(7, 13, 11, 0.96)",
    justifyContent: "space-between",
  },
  lightboxHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 24,
    paddingTop: Platform.OS === "ios" ? 54 : 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.08)",
  },
  lightboxTitleArea: {
    flex: 1,
    marginRight: 16,
  },
  lightboxTitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontFamily: fonts.bold,
  },
  lightboxSubtitle: {
    color: "rgba(255, 255, 255, 0.6)",
    fontSize: 13,
    fontFamily: fonts.regular,
    marginTop: 2,
  },
  lightboxCloseBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.12)",
    alignItems: "center",
    justifyContent: "center",
  },
  lightboxMainArea: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    paddingHorizontal: 16,
  },
  lightboxImage: {
    width: "100%",
    height: "100%",
    maxHeight: 650,
  },
  lightboxNavBtn: {
    position: "absolute",
    zIndex: 20,
    top: "50%",
    marginTop: -26,
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "rgba(11, 26, 23, 0.8)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
    ...shadow,
  },
  lightboxNavBtnLeft: {
    left: 20,
  },
  lightboxNavBtnRight: {
    right: 20,
  },
  lightboxThumbStrip: {
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.08)",
    backgroundColor: "rgba(0, 0, 0, 0.4)",
  },
  lightboxThumbScrollContent: {
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 20,
    alignItems: "center",
  },
  lightboxThumbCard: {
    width: 76,
    height: 52,
    borderRadius: 8,
    overflow: "hidden",
    borderWidth: 2,
    borderColor: "transparent",
    opacity: 0.6,
  },
  lightboxThumbCardActive: {
    borderColor: "#04cf92",
    opacity: 1,
  },
  overviewHeaderCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    borderWidth: 0.8,
    borderColor: "rgba(11,26,23,0.08)",
    padding: 24,
    gap: 12,
    overflow: "hidden",
  },
  titleCategoryRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  categoryBadge: {
    backgroundColor: "#E6FAF4",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  categoryBadgeText: {
    fontSize: 12,
    fontFamily: fonts.semiBold,
    color: "#04cf92",
  },
  verifiedSmallBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  verifiedSmallText: {
    fontSize: 12,
    fontFamily: fonts.semiBold,
    color: "#04cf92",
  },
  propertyTitle: {
    fontSize: 24,
    fontFamily: fonts.extraBold,
    color: "#0B1A17",
    letterSpacing: -0.4,
  },
  locationSubRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  locationSubText: {
    fontSize: 14,
    fontFamily: fonts.regular,
    color: "#5C6B66",
  },
  keySpecsRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    marginTop: 8,
    gap: 12,
    rowGap: 8,
  },
  specItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexShrink: 1,
  },
  specText: {
    fontSize: 14,
    fontFamily: fonts.semiBold,
    color: "#0B1A17",
  },
  specDivider: {
    width: 1,
    height: 16,
    backgroundColor: "rgba(11,26,23,0.15)",
  },
  aiValuationCard: {
    backgroundColor: "#E6FAF4",
    borderRadius: 24,
    padding: 24,
    gap: 10,
  },
  aiValuationHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  aiValuationTitle: {
    fontSize: 16,
    fontFamily: fonts.bold,
    color: "#04cf92",
  },
  aiValuationDesc: {
    fontSize: 14,
    fontFamily: fonts.regular,
    color: "#0B1A17",
    lineHeight: 20,
  },
  boldText: {
    fontFamily: fonts.bold,
  },
  aiTrendBadge: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#FFFFFF",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 4,
    marginTop: 4,
  },
  aiTrendText: {
    fontSize: 12,
    fontFamily: fonts.semiBold,
    color: "#04cf92",
  },
  sectionCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    borderWidth: 0.8,
    borderColor: "rgba(11,26,23,0.08)",
    padding: 24,
    gap: 16,
  },
  sectionHeading: {
    fontSize: 18,
    fontFamily: fonts.bold,
    color: "#0B1A17",
  },
  sectionHeaderBetween: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  seeAllLink: {
    fontSize: 14,
    fontFamily: fonts.semiBold,
    color: "#04cf92",
  },
  descriptionParagraph: {
    fontSize: 14,
    fontFamily: fonts.regular,
    color: "#5C6B66",
    lineHeight: 22,
  },
  amenitiesCheckGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
    marginTop: 8,
  },
  amenityCheckItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    width: "45%",
  },
  amenityCheckText: {
    fontSize: 14,
    fontFamily: fonts.regular,
    color: "#0B1A17",
  },
  mapCard: {
    height: 320,
    borderRadius: 16,
    overflow: "hidden",
    position: "relative",
    borderWidth: 1,
    borderColor: "rgba(11,26,23,0.08)",
    backgroundColor: "#E8EEEC",
  },
  openMapsBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#E6FAF4",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
  },
  openMapsBtnText: {
    color: "#04cf92",
    fontSize: 13,
    fontFamily: fonts.semiBold,
  },
  mapAddressPill: {
    position: "absolute",
    bottom: 12,
    left: 12,
    maxWidth: "85%",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
    borderWidth: 0.5,
    borderColor: "rgba(11,26,23,0.1)",
  },
  mapAddressPillText: {
    color: "#0B1A17",
    fontSize: 12,
    fontFamily: fonts.semiBold,
  },
  nativeMapContainer: {
    width: "100%",
    height: "100%",
    position: "relative",
  },
  mapImage: {
    width: "100%",
    height: "100%",
  },
  mapPinOverlay: {
    position: "absolute",
    top: "30%",
    left: "35%",
    alignItems: "center",
    gap: 6,
  },
  mapTooltip: {
    backgroundColor: "#0B1A17",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  mapTooltipText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontFamily: fonts.semiBold,
  },
  mapPinCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#04cf92",
    alignItems: "center",
    justifyContent: "center",
  },
  nearbyGrid: {
    flexDirection: "row",
    gap: 12,
  },
  poiCard: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: "#E8EEFC",
    borderRadius: 16,
    padding: 12,
  },
  poiIconBg: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  poiName: {
    fontSize: 13,
    fontFamily: fonts.semiBold,
    color: "#0B1A17",
  },
  poiDist: {
    fontSize: 11,
    fontFamily: fonts.regular,
    color: "#5C6B66",
  },
  similarScroll: {
    width: "100%",
  },
  similarRow: {
    flexDirection: "row",
    gap: 16,
  },
  similarCard: {
    width: 220,
    backgroundColor: "#FAFBFB",
    borderRadius: 16,
    overflow: "hidden",
    borderWidth: 0.8,
    borderColor: "rgba(11,26,23,0.08)",
  },
  similarThumb: {
    width: "100%",
    height: 130,
  },
  similarInfo: {
    padding: 12,
    gap: 4,
  },
  similarPriceRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  similarPrice: {
    fontSize: 15,
    fontFamily: fonts.bold,
    color: "#04cf92",
  },
  similarScoreBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  similarScoreText: {
    fontSize: 12,
    fontFamily: fonts.bold,
    color: "#04cf92",
  },
  similarTitle: {
    fontSize: 13,
    fontFamily: fonts.semiBold,
    color: "#0B1A17",
  },
  similarLoc: {
    fontSize: 12,
    fontFamily: fonts.regular,
    color: "#5C6B66",
  },
  similarSpecs: {
    fontSize: 11,
    fontFamily: fonts.regular,
    color: "#5C6B66",
    marginTop: 4,
  },
  sellerCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    borderWidth: 0.8,
    borderColor: "rgba(11,26,23,0.08)",
    padding: 24,
    gap: 16,
  },
  sellerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  sellerAvatar: {
    width: 54,
    height: 54,
    borderRadius: 27,
  },
  similarRequestState: { alignItems: "center", flexDirection: "row", gap: 8, paddingVertical: 14 },
  sellerAvatarPlaceholder: {
    alignItems: "center",
    backgroundColor: "#E8EEEC",
    justifyContent: "center",
  },
  sellerName: {
    fontSize: 16,
    fontFamily: fonts.bold,
    color: "#0B1A17",
  },
  sellerAgency: {
    fontSize: 13,
    fontFamily: fonts.regular,
    color: "#5C6B66",
  },
  priceCalloutWrap: {
    backgroundColor: "#F4F6F5",
    borderRadius: 16,
    padding: 16,
    gap: 4,
  },
  priceCalloutHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  priceCalloutLabel: {
    fontSize: 12,
    fontFamily: fonts.semiBold,
    color: "#5C6B66",
  },
  scoreBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  scoreBadgeText: {
    fontSize: 14,
    fontFamily: fonts.bold,
    color: "#04cf92",
  },
  priceCalloutValue: {
    fontSize: 22,
    fontFamily: fonts.extraBold,
    color: "#0B1A17",
  },
  priceCalloutPeriod: {
    fontSize: 14,
    fontFamily: fonts.regular,
    color: "#5C6B66",
  },
  sellerActionsRow: {
    flexDirection: "row",
    gap: 12,
  },
  sellerActionBtn: {
    flex: 1,
    height: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(11,26,23,0.12)",
    backgroundColor: "#FFFFFF",
  },
  actionBtnDisabled: {
    opacity: 0.45,
  },
  sellerActionText: {
    fontSize: 14,
    fontFamily: fonts.semiBold,
    color: "#0B1A17",
  },
  whatsAppActionBtn: {
    flex: 1.25,
    height: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderRadius: 999,
    backgroundColor: "#F0FDF4",
    borderWidth: 1.2,
    borderColor: "#25D366",
    shadowColor: "#25D366",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 2,
  },
  whatsAppActionText: {
    fontSize: 14,
    fontFamily: fonts.bold,
    color: "#166534",
  },
  bookVisitBtn: {
    height: 46,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#F4823A",
    borderRadius: 999,
  },
  bookVisitBtnText: {
    color: colorTokens.onAccent,
    fontSize: 15,
    fontFamily: fonts.bold,
  },
  aiRecCard: {
    backgroundColor: "#E6FAF4",
    borderRadius: 24,
    padding: 24,
    gap: 10,
  },
  aiRecHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  aiRecTitle: {
    fontSize: 15,
    fontFamily: fonts.bold,
    color: "#04cf92",
  },
  aiRecBody: {
    fontSize: 13,
    fontFamily: fonts.regular,
    color: "#0B1A17",
    lineHeight: 19,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  modalContent: {
    width: "100%",
    maxWidth: 420,
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 24,
    gap: 16,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  modalTitle: {
    fontSize: 18,
    fontFamily: fonts.bold,
    color: "#0B1A17",
  },
  closeBtn: {
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
  },
  modalBodyText: {
    fontSize: 14,
    fontFamily: fonts.regular,
    color: "#5C6B66",
    lineHeight: 20,
  },
  modalNoPhoneText: {
    fontSize: 13,
    fontFamily: fonts.medium,
    color: colorTokens.warningText,
    lineHeight: 18,
  },
  confirmVisitBtn: {
    height: 44,
    flexDirection: "row",
    gap: 8,
    backgroundColor: colorTokens.brand,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
  },
  confirmVisitBtnDisabled: {
    backgroundColor: colorTokens.surfaceSunken,
    borderWidth: 1,
    borderColor: colorTokens.divider,
  },
  confirmVisitText: {
    color: colorTokens.onBrand,
    fontSize: 14,
    fontFamily: fonts.bold,
  },
  confirmVisitTextDisabled: {
    color: colorTokens.subtle,
  },
  modalDivider: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginVertical: 4,
  },
  modalDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: "rgba(11,26,23,0.08)",
  },
  modalDividerText: {
    fontSize: 12,
    fontFamily: fonts.semiBold,
    color: "#5C6B66",
  },
  modalCallBtn: {
    height: 44,
    borderRadius: 999,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: colorTokens.divider,
    backgroundColor: colorTokens.surface,
  },
  modalCallBtnDisabled: {
    backgroundColor: colorTokens.surfaceSunken,
    borderColor: colorTokens.divider,
  },
  modalCallBtnText: {
    fontSize: 14,
    fontFamily: fonts.bold,
    color: colorTokens.ink,
  },
  modalCallBtnTextDisabled: {
    color: colorTokens.subtle,
  },
});
