import { Platform, StyleSheet } from 'react-native';
import { colors, radius, fonts } from '../../theme';

export const styles = StyleSheet.create({
  sectionRoot: {
    width: '100%',
    backgroundColor: '#F8FAF9',
    paddingVertical: 84,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 0, 0, 0.05)',
  },
  marketPositionStrip: {
    width: '100%',
    backgroundColor: '#0B1A17',
    paddingVertical: 10,
    alignItems: 'center',
    marginBottom: 40,
  },
  marketPositionText: {
    fontFamily: fonts.semiBold,
    fontSize: 13,
    color: '#04CF92',
    letterSpacing: 0.5,
  },
  innerContainer: {
    maxWidth: 1240,
    width: '100%',
    marginHorizontal: 'auto',
    paddingHorizontal: 28,
  },
  innerContainerTablet: {
    paddingHorizontal: 20,
  },
  headerBlock: {
    alignItems: 'center',
    textAlign: 'center',
    maxWidth: 820,
    marginHorizontal: 'auto',
    marginBottom: 56,
  },
  eyebrowBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: radius.pill,
    backgroundColor: 'rgba(15, 109, 85, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(15, 109, 85, 0.2)',
    marginBottom: 16,
  },
  eyebrowText: {
    fontFamily: fonts.semiBold,
    fontSize: 12,
    color: '#0F6D55',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  sectionTitle: {
    fontFamily: fonts.bold,
    fontSize: 38,
    lineHeight: 46,
    color: colors.ink,
    textAlign: 'center',
    letterSpacing: -0.8,
    marginBottom: 16,
  },
  sectionTitlePhone: {
    fontSize: 28,
    lineHeight: 34,
    letterSpacing: -0.4,
  },
  sectionSubtitle: {
    fontFamily: fonts.regular,
    fontSize: 17,
    lineHeight: 26,
    color: colors.muted,
    textAlign: 'center',
  },
  sectionSubtitlePhone: {
    fontSize: 15,
    lineHeight: 22,
  },
  flagshipGrid: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 36,
    width: '100%',
  },
  flagshipGridTablet: {
    flexDirection: 'column',
    gap: 32,
  },
  headlinesCol: {
    flex: 1,
    gap: 16,
    width: '100%',
  },
  headlineCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: radius.lg,
    padding: 24,
    borderWidth: 1.5,
    borderColor: 'rgba(11, 26, 23, 0.08)',
    ...(Platform.OS === 'web'
      ? {
          cursor: 'pointer',
          transition: 'border-color 0.2s ease, box-shadow 0.2s ease, transform 0.2s ease',
        }
      : {}),
  },
  headlineCardActive: {
    borderColor: '#0F6D55',
    backgroundColor: '#FFFFFF',
    shadowColor: '#0F6D55',
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 14,
  },
  headlineCardHovered: {
    transform: [{ translateY: -2 }],
    borderColor: 'rgba(15, 109, 85, 0.4)',
  },
  cardTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  headlineIconBox: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(15, 109, 85, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headlineTagPill: {
    backgroundColor: 'rgba(15, 109, 85, 0.06)',
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: radius.pill,
  },
  headlineTagText: {
    fontFamily: fonts.medium,
    fontSize: 11,
    color: '#0F6D55',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  headlineItemTitle: {
    fontFamily: fonts.bold,
    fontSize: 18,
    color: colors.ink,
    marginBottom: 8,
    letterSpacing: -0.2,
  },
  headlineItemDesc: {
    fontFamily: fonts.regular,
    fontSize: 14,
    lineHeight: 22,
    color: colors.muted,
    marginBottom: 14,
  },
  examplesList: {
    gap: 6,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0, 0, 0, 0.04)',
  },
  exampleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  exampleText: {
    flex: 1,
    fontFamily: fonts.regular,
    fontSize: 13,
    lineHeight: 19,
    color: colors.ink,
  },
  demoCol: {
    flex: 1.15,
    width: '100%',
  },
  deviceFrame: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(11, 26, 23, 0.1)',
    shadowColor: '#000',
    shadowOpacity: 0.07,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 24,
    overflow: 'hidden',
  },
  deviceChromeBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F3F5F4',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0, 0, 0, 0.06)',
  },
  chromeDotsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  chromeDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  deviceChromeTitle: {
    fontFamily: fonts.medium,
    fontSize: 12,
    color: colors.muted,
  },
  replayBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(15, 109, 85, 0.08)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: radius.pill,
    ...(Platform.OS === 'web' ? { cursor: 'pointer' } : {}),
  },
  replayBtnText: {
    fontFamily: fonts.semiBold,
    fontSize: 11,
    color: '#0F6D55',
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 14,
    gap: 12,
  },
  sheetHeaderIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: 'rgba(15, 109, 85, 0.09)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetHeaderTextWrap: {
    flex: 1,
  },
  sheetHeaderTitle: {
    fontFamily: fonts.bold,
    fontSize: 16,
    color: colors.ink,
  },
  sheetHeaderSubtitle: {
    fontFamily: fonts.regular,
    fontSize: 13,
    color: colors.muted,
    marginTop: 2,
  },
  sheetDivider: {
    height: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.06)',
  },
  sheetBody: {
    padding: 20,
  },
  inputStage: {
    gap: 14,
  },
  textareaWrap: {
    position: 'relative',
    borderWidth: 1.5,
    borderColor: 'rgba(11, 26, 23, 0.15)',
    borderRadius: radius.md,
    backgroundColor: '#FAFBFB',
    padding: 12,
  },
  sheetTextarea: {
    fontFamily: fonts.regular,
    fontSize: 14,
    lineHeight: 22,
    color: colors.ink,
    minHeight: 110,
    outlineWidth: 0,
  },
  typingCursor: {
    position: 'absolute',
    bottom: 14,
    right: 14,
    width: 2,
    height: 16,
    backgroundColor: '#0F6D55',
  },
  charCountRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  charCountText: {
    fontFamily: fonts.medium,
    fontSize: 12,
    color: colors.muted,
  },
  analyzeBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#04CF92',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: radius.pill,
    ...(Platform.OS === 'web'
      ? {
          cursor: 'pointer',
          transition: 'all 0.15s ease',
        }
      : {}),
  },
  analyzeBtnHovered: {
    backgroundColor: '#04BD84',
    transform: [{ translateY: -1 }],
  },
  analyzeBtnText: {
    fontFamily: fonts.bold,
    fontSize: 14,
    color: '#0B1A17',
  },
  analyzingStateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    backgroundColor: 'rgba(15, 109, 85, 0.06)',
    borderRadius: radius.pill,
    gap: 10,
  },
  analyzingText: {
    fontFamily: fonts.medium,
    fontSize: 13,
    color: '#0F6D55',
  },
  previewStage: {
    gap: 16,
  },
  conversionBanner: {
    backgroundColor: 'rgba(15, 109, 85, 0.07)',
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: 'rgba(15, 109, 85, 0.2)',
    padding: 10,
  },
  conversionTag: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 6,
  },
  conversionTagLabel: {
    fontFamily: fonts.medium,
    fontSize: 11,
    color: colors.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  conversionTagValue: {
    fontFamily: fonts.bold,
    fontSize: 13,
    color: '#0F6D55',
  },
  fieldSection: {
    gap: 8,
  },
  fieldSectionTitle: {
    fontFamily: fonts.semiBold,
    fontSize: 12,
    color: colors.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginBottom: 2,
  },
  fieldRow: {
    gap: 4,
  },
  fieldRowTwoCol: {
    flexDirection: 'row',
    gap: 10,
  },
  colHalf: {
    flex: 1,
    gap: 4,
  },
  fieldRowThreeCol: {
    flexDirection: 'row',
    gap: 8,
  },
  colThird: {
    flex: 1,
    gap: 4,
  },
  fieldLabel: {
    fontFamily: fonts.medium,
    fontSize: 12,
    color: colors.muted,
  },
  labelWithBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  resolvedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(15, 109, 85, 0.08)',
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 6,
  },
  resolvedBadgeText: {
    fontFamily: fonts.medium,
    fontSize: 11,
    color: '#0F6D55',
  },
  lowConfBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FEF6E9',
    borderWidth: 1,
    borderColor: 'rgba(212, 135, 10, 0.3)',
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 6,
  },
  lowConfText: {
    fontFamily: fonts.medium,
    fontSize: 11,
    color: '#D4870A',
  },
  fieldValueBox: {
    backgroundColor: '#F8FAF9',
    borderRadius: radius.sm,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.06)',
  },
  fieldValueBoxEditable: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FEFDFB',
    borderRadius: radius.sm,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: 'rgba(212, 135, 10, 0.35)',
    ...(Platform.OS === 'web' ? { cursor: 'pointer' } : {}),
  },
  fieldValueText: {
    fontFamily: fonts.regular,
    fontSize: 13,
    color: colors.ink,
  },
  fieldValueTextLow: {
    fontFamily: fonts.medium,
    color: '#8A5300',
  },
  fieldEditRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  fieldEditInput: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#0F6D55',
    borderRadius: radius.sm,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontFamily: fonts.regular,
    fontSize: 13,
    color: colors.ink,
    outlineWidth: 0,
  },
  fieldEditDone: {
    width: 32,
    height: 32,
    borderRadius: radius.sm,
    backgroundColor: 'rgba(15, 109, 85, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    ...(Platform.OS === 'web' ? { cursor: 'pointer' } : {}),
  },
  amenityChipsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  amenityChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(15, 109, 85, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(15, 109, 85, 0.2)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: radius.pill,
  },
  amenityChipText: {
    fontFamily: fonts.medium,
    fontSize: 12,
    color: '#0F6D55',
    textTransform: 'capitalize',
  },
  sheetActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 10,
    gap: 12,
  },
  tryAgainBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: radius.pill,
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.15)',
    backgroundColor: '#FFFFFF',
    ...(Platform.OS === 'web' ? { cursor: 'pointer', transition: 'all 0.15s ease' } : {}),
  },
  tryAgainBtnHovered: {
    borderColor: colors.ink,
  },
  tryAgainText: {
    fontFamily: fonts.semiBold,
    fontSize: 13,
    color: colors.muted,
  },
  applyBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#04CF92',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: radius.pill,
    ...(Platform.OS === 'web' ? { cursor: 'pointer', transition: 'all 0.15s ease' } : {}),
  },
  applyBtnHovered: {
    backgroundColor: '#04BD84',
    transform: [{ translateY: -1 }],
  },
  applyBtnText: {
    fontFamily: fonts.bold,
    fontSize: 13,
    color: '#0B1A17',
  },
  sheetDisclaimer: {
    fontFamily: fonts.regular,
    fontSize: 11,
    color: colors.muted,
    textAlign: 'center',
    marginTop: 4,
  },
});
