import { Platform, StyleSheet } from "react-native";
import { colorTokens, fonts, webPointer } from "@/theme";

export const styles = StyleSheet.create({
  outerContainer: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: "#F8FAF9",
  },
  workspaceScroll: {
    flexGrow: 1,
    justifyContent: "space-between",
  },
  // Desktop Sidebar
  sidebar: {
    width: 256,
    backgroundColor: "#FFFFFF",
    borderRightWidth: 0.8,
    borderRightColor: "rgba(11,26,23,0.08)",
    paddingVertical: 20,
    paddingHorizontal: 16,
  },
  sidebarHeader: {
    gap: 16,
    marginBottom: 16,
    paddingHorizontal: 8,
  },
  sellerRolePill: {
    backgroundColor: "#E8EEFC",
    borderRadius: 999,
    paddingVertical: 4,
    paddingHorizontal: 12,
    alignItems: "center",
  },
  sellerRoleText: {
    color: "#2251D6",
    fontSize: 12,
    fontFamily: fonts.semiBold,
  },
  sidebarNavScroll: {
    gap: 2,
    paddingVertical: 8,
  },
  navItem: {
    minHeight: 42,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    ...webPointer,
  },
  navItemActive: {
    backgroundColor: "#E6FAF4",
  },
  navItemDanger: {
    marginTop: 8,
  },
  navItemText: {
    flex: 1,
    fontSize: 14,
    fontFamily: fonts.semiBold,
    color: "#5C6B66",
  },
  navItemTextActive: {
    color: "#04cf92",
    fontFamily: fonts.bold,
  },
  navItemTextDanger: {
    color: "#D4183D",
  },
  // Main Content
  mainContent: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    backgroundColor: "#F8FAF9",
  },
  topHeader: {
    minHeight: 68,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(11,26,23,0.06)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 24,
    paddingVertical: 12,
    gap: 16,
  },
  headerTitleGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 18,
    flex: 1,
    minWidth: 0,
  },
  desktopBrandLink: {
    flexShrink: 0,
  },
  headerTitle: {
    fontSize: 20,
    fontFamily: fonts.headingBold,
    fontWeight: "700",
    color: "#0B1A17",
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flexShrink: 0,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#F4F6F5",
    borderRadius: 999,
    paddingHorizontal: 14,
    width: 220,
    height: 38,
    borderWidth: 0.8,
    borderColor: "rgba(11,26,23,0.08)",
  },
  searchInput: {
    flex: 1,
    height: "100%",
    fontSize: 13,
    fontFamily: fonts.regular,
    fontWeight: "300",
    color: "rgba(11, 26, 23, 0.45)",
    paddingVertical: 0,
    ...(Platform.OS === "web" ? ({ outlineStyle: "none" } as any) : {}),
  },
  textInputNormal: {
    fontWeight: "400",
    color: "#0B1A17",
  },
  iconCircleBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "rgba(11,26,23,0.08)",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    ...webPointer,
  },
  headerDotIndicator: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#F4823A",
    borderWidth: 1.5,
    borderColor: "#FFFFFF",
  },
  viewSiteBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    height: 38,
    borderRadius: 999,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "rgba(11,26,23,0.08)",
    ...webPointer,
  },
  viewSiteText: {
    fontSize: 13,
    fontFamily: fonts.semiBold,
    fontWeight: "600",
    color: "#0B1A17",
  },
  // Scrollable Content
  scrollContent: {
    paddingHorizontal: 20,
    paddingVertical: 24,
    alignItems: "center",
  },
  scrollContentPhone: {
    paddingHorizontal: 12,
    paddingVertical: 16,
  },
  contentWrap: {
    width: "100%",
    maxWidth: 768,
  },
  // Segmented Tab Switcher (Buyer & Seller)
  tabBar: {
    flexDirection: "row",
    backgroundColor: "#EBEFEA",
    borderRadius: 14,
    padding: 4,
    marginBottom: 20,
    width: "100%",
    gap: 6,
  },
  tabBarPhone: {
    marginBottom: 16,
  },
  tabBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 10,
    borderRadius: 10,
  },
  tabBtnActive: {
    backgroundColor: "#0F6D55",
    ...(Platform.OS === "web"
      ? {
          boxShadow: "0 2px 8px rgba(15, 109, 85, 0.25)",
        }
      : {
          elevation: 2,
        }),
  },
  tabBtnText: {
    fontSize: 14,
    fontFamily: fonts.semiBold,
    fontWeight: "600",
    color: "#5C6B66",
  },
  tabBtnTextPhone: {
    fontSize: 13,
  },
  tabBtnTextActive: {
    color: "#FFFFFF",
  },
  // Cards
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    borderWidth: 1.13,
    borderColor: "rgba(11,26,23,0.08)",
    padding: 24,
    ...(Platform.OS === "web"
      ? {
          boxShadow: "0px 2px 8px rgba(11, 26, 23, 0.04)",
        }
      : {
          elevation: 1,
          shadowColor: "#000",
          shadowOffset: { width: 0, height: 1 },
          shadowOpacity: 0.03,
          shadowRadius: 3,
        }),
  },
  cardPhone: {
    padding: 16,
    borderRadius: 18,
  },
  sectionSpacing: {
    marginTop: 20,
  },
  cardHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 20,
  },
  cardTitle: {
    fontSize: 18,
    fontFamily: fonts.headingBold,
    fontWeight: "700",
    color: "#0B1A17",
    letterSpacing: -0.36,
  },
  // Profile Row
  profileRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    marginBottom: 20,
  },
  profileRowPhone: {
    gap: 12,
  },
  avatarWrap: {
    width: 80,
    height: 80,
    borderRadius: 24,
    overflow: "hidden",
    backgroundColor: "#E2E8F0",
    position: "relative",
  },
  avatarWrapPhone: {
    width: 64,
    height: 64,
    borderRadius: 18,
  },
  avatarImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  uploadingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.4)",
    alignItems: "center",
    justifyContent: "center",
  },
  profileInfoCol: {
    flex: 1,
    justifyContent: "center",
  },
  nameBadgeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  profileName: {
    fontSize: 16,
    fontFamily: fonts.semiBold,
    fontWeight: "600",
    color: "#0B1A17",
  },
  verifiedBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#E7F2EE",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
  },
  verifiedText: {
    fontSize: 12,
    fontFamily: fonts.regular,
    color: "#0F6D55",
    fontWeight: "500",
  },
  unverifiedBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#FEF3C7",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(217, 119, 6, 0.2)",
  },
  unverifiedText: {
    fontSize: 12,
    fontFamily: fonts.regular,
    color: "#D97706",
    fontWeight: "500",
  },
  buyerBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#E7F2EE",
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 999,
  },
  buyerBadgeText: {
    fontSize: 12,
    fontFamily: fonts.medium,
    color: "#0F6D55",
    fontWeight: "600",
  },
  changePhotoBtn: {
    alignSelf: "flex-start",
    marginTop: 6,
  },
  changePhotoText: {
    fontSize: 14,
    fontFamily: fonts.semiBold,
    fontWeight: "600",
    color: "#0F6D55",
  },
  // Form Inputs
  formGroup: {
    width: "100%",
  },
  formGroupSpacing: {
    marginTop: 16,
  },
  fieldLabel: {
    fontSize: 14,
    fontFamily: fonts.medium,
    fontWeight: "500",
    color: "#0B1A17",
    marginBottom: 8,
  },
  inputWrap: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F4F6F5",
    borderRadius: 16,
    height: 48,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: "rgba(11,26,23,0.06)",
  },
  inputWrapPhone: {
    height: 44,
    paddingHorizontal: 12,
  },
  textInput: {
    flex: 1,
    height: "100%",
    fontSize: 14,
    fontFamily: fonts.regular,
    fontWeight: "300",
    color: "rgba(11, 26, 23, 0.45)",
    paddingVertical: 0,
    ...(Platform.OS === "web" ? ({ outlineStyle: "none" } as any) : {}),
  },
  clearBtn: {
    padding: 6,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 8,
  },
  // Quick Chips
  quickChipsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
    marginTop: 18,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: "rgba(11,26,23,0.06)",
  },
  quickChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: "#F4F6F5",
    borderWidth: 1,
    borderColor: "rgba(11,26,23,0.08)",
  },
  quickChipText: {
    fontSize: 12.5,
    fontFamily: fonts.medium,
    color: "#0B1A17",
    fontWeight: "500",
  },
  // Account Security
  securityRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    paddingVertical: 4,
  },
  securityRowPhone: {
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 12,
  },
  securityInfoCol: {
    flex: 1,
    minWidth: 0,
  },
  securityTitle: {
    fontSize: 15,
    fontFamily: fonts.semiBold,
    fontWeight: "600",
    color: "#0B1A17",
  },
  securityDesc: {
    fontSize: 13,
    fontFamily: fonts.regular,
    color: "#5C6B66",
    marginTop: 3,
    lineHeight: 18,
  },
  securityDivider: {
    height: 1,
    backgroundColor: "rgba(11,26,23,0.06)",
    marginVertical: 14,
  },
  changePasswordBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 999,
    borderWidth: 1.2,
    borderColor: "rgba(4, 207, 146, 0.35)",
    backgroundColor: "rgba(4, 207, 146, 0.12)",
  },
  changePasswordBtnText: {
    fontSize: 13.5,
    fontFamily: fonts.semiBold,
    fontWeight: "600",
    color: "#03a675",
  },
  deleteAccountBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 999,
    borderWidth: 1.2,
    borderColor: "rgba(212, 24, 61, 0.3)",
    backgroundColor: "#FFF5F6",
  },
  deleteAccountBtnText: {
    fontSize: 13.5,
    fontFamily: fonts.semiBold,
    fontWeight: "600",
    color: "#D4183D",
  },
  fullWidthBtnPhone: {
    alignSelf: "stretch",
    justifyContent: "center",
  },
  // Bottom Action Row
  actionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    paddingTop: 24,
    paddingBottom: 40,
    width: "100%",
    gap: 12,
  },
  actionRowPhone: {
    paddingTop: 20,
    paddingBottom: 32,
  },
  logoutBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1.13,
    borderColor: "rgba(212,24,61,0.3)",
    backgroundColor: "#FFFFFF",
  },
  logoutBtnPhone: {
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  logoutBtnText: {
    fontSize: 14,
    fontFamily: fonts.semiBold,
    fontWeight: "600",
    color: "#D4183D",
  },
  saveBtn: {
    backgroundColor: "#04cf92",
    paddingHorizontal: 24,
    paddingVertical: 11,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    minWidth: 130,
  },
  saveBtnPhone: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    minWidth: 110,
  },
  btnDisabled: {
    opacity: 0.7,
  },
  saveBtnText: {
    fontSize: 14,
    fontFamily: fonts.semiBold,
    fontWeight: "600",
    color: colorTokens.onBrand,
  },
  // Change Password Modal
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(11, 26, 23, 0.45)",
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
    zIndex: 100,
  },
  modalCard: {
    width: "100%",
    maxWidth: 440,
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 24,
    borderWidth: 1,
    borderColor: "rgba(11, 26, 23, 0.08)",
    ...(Platform.OS === "web"
      ? {
          boxShadow: "0 20px 45px -10px rgba(11, 26, 23, 0.25)",
        }
      : {
          elevation: 10,
        }),
  },
  modalCardPhone: {
    padding: 18,
    borderRadius: 20,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    marginBottom: 18,
  },
  modalIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "rgba(4, 207, 146, 0.14)",
    alignItems: "center",
    justifyContent: "center",
  },
  modalTitleWrap: {
    flex: 1,
  },
  modalTitle: {
    fontSize: 18,
    fontFamily: fonts.headingBold,
    fontWeight: "700",
    color: "#0B1A17",
  },
  modalSubtitle: {
    fontSize: 13,
    fontFamily: fonts.regular,
    color: "#5C6B66",
    marginTop: 2,
    lineHeight: 18,
  },
  modalCloseBtn: {
    padding: 4,
  },
  modalErrorBanner: {
    backgroundColor: "#FFF5F6",
    borderWidth: 1,
    borderColor: "rgba(212, 24, 61, 0.2)",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 14,
  },
  modalErrorText: {
    fontSize: 13,
    fontFamily: fonts.medium,
    color: "#D4183D",
  },
  modalInputGroup: {
    width: "100%",
  },
  modalFieldLabel: {
    fontSize: 13,
    fontFamily: fonts.medium,
    fontWeight: "500",
    color: "#0B1A17",
    marginBottom: 6,
  },
  modalInputWrap: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F4F6F5",
    borderRadius: 12,
    height: 44,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: "rgba(11,26,23,0.06)",
  },
  modalTextInput: {
    flex: 1,
    height: "100%",
    fontSize: 14,
    fontFamily: fonts.regular,
    color: "#0B1A17",
    paddingVertical: 0,
    ...(Platform.OS === "web" ? ({ outlineStyle: "none" } as any) : {}),
  },
  eyeBtn: {
    padding: 6,
  },
  modalActionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 10,
    marginTop: 22,
  },
  modalCancelBtn: {
    paddingHorizontal: 16,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: "#F4F6F5",
  },
  modalCancelBtnText: {
    fontSize: 13.5,
    fontFamily: fonts.medium,
    color: "#5C6B66",
  },
  modalSubmitBtn: {
    paddingHorizontal: 20,
    paddingVertical: 9,
    borderRadius: 999,
    backgroundColor: "#04cf92",
  },
  modalSubmitBtnText: {
    fontSize: 13.5,
    fontFamily: fonts.semiBold,
    color: colorTokens.onBrand,
    fontWeight: "600",
  },
  pressed: {
    opacity: 0.85,
  },
});
