import { StyleSheet } from "react-native";
import { colorTokens, colors, fonts, radius } from "@/theme";

export const styles = StyleSheet.create({
  pressed: { opacity: 0.85 },
  workspaceScroll: {
    flexGrow: 1,
    justifyContent: "space-between",
  },
  outerContainer: {
    width: "100%",
    flex: 1,
    flexDirection: "row",
    backgroundColor: "#F8FAF9",
  },
  sidebar: {
    width: 256,
    backgroundColor: colors.white,
    borderRightWidth: 0.8,
    borderRightColor: "rgba(11,26,23,0.08)",
    paddingVertical: 20,
    paddingHorizontal: 16,
  },
  sidebarHeader: {
    gap: 16,
    marginBottom: 16,
    paddingHorizontal: 8,
  },
  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  brandIconBg: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.green,
    alignItems: "center",
    justifyContent: "center",
  },
  brandText: {
    fontSize: 18,
    fontFamily: fonts.extraBold,
    color: colors.ink,
  },
  brandTextAccent: {
    color: colors.green,
  },
  sellerRolePill: {
    backgroundColor: colors.blueLight,
    borderRadius: 999,
    paddingVertical: 4,
    paddingHorizontal: 12,
    alignItems: "center",
  },
  sellerRoleText: {
    color: colors.blue,
    fontSize: 12,
    fontFamily: fonts.semiBold,
  },
  sidebarNavScroll: {
    gap: 2,
    paddingVertical: 8,
  },
  navItem: {
    minHeight: 42,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
  },
  navItemActive: {
    backgroundColor: colors.greenLight,
  },
  navItemDanger: {
    marginTop: 8,
  },
  navItemText: {
    flex: 1,
    fontSize: 14,
    fontFamily: fonts.semiBold,
    color: colors.muted,
  },
  navItemTextActive: {
    color: colors.green,
    fontFamily: fonts.bold,
  },
  navItemTextDanger: {
    color: "#D4183D",
  },
  badgeCountPill: {
    backgroundColor: colors.orange,
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  badgeCountText: {
    color: colors.white,
    fontSize: 12,
    fontFamily: fonts.bold,
  },
  mainContent: {
    flex: 1,
    minWidth: 0,
    flexDirection: "column",
  },
  topHeader: {
    minHeight: 64,
    backgroundColor: "rgba(255,255,255,0.92)",
    borderBottomWidth: 0.8,
    borderBottomColor: "rgba(11,26,23,0.08)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 24,
    paddingVertical: 12,
  },
  headerTitle: {
    fontSize: 19,
    fontFamily: fonts.extraBold,
    color: colors.ink,
    letterSpacing: -0.38,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  searchContainer: {
    width: 256,
    height: 38,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#F4F6F5",
    borderRadius: 999,
    borderWidth: 0.8,
    borderColor: "rgba(11,26,23,0.08)",
    paddingHorizontal: 13,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    fontFamily: fonts.regular,
    color: colors.ink,
  },
  iconCircleBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 0.8,
    borderColor: "rgba(11,26,23,0.08)",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  headerDotIndicator: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.orange,
  },

  scrollBody: {
    padding: 24,
    gap: 24,
  },
  scrollBodyPhone: {
    padding: 16,
    gap: 16,
  },
  heroBanner: {
    borderRadius: 24,
    padding: 32,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    position: "relative",
    overflow: "hidden",
  },
  heroContentLeft: {
    flex: 1,
    maxWidth: 580,
    gap: 6,
  },
  heroSubtitle: {
    fontSize: 14,
    color: "rgba(255,255,255,0.8)",
    fontFamily: fonts.regular,
  },
  heroTitle: {
    fontSize: 26,
    color: colors.white,
    fontFamily: fonts.extraBold,
    letterSpacing: -0.5,
  },
  heroDescription: {
    marginTop: 6,
    fontSize: 14,
    color: "rgba(255,255,255,0.88)",
    fontFamily: fonts.regular,
    lineHeight: 20,
  },
  boldSpan: {
    fontFamily: fonts.bold,
  },
  heroButtonRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 18,
  },
  heroBtnPrimary: {
    height: 40,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: colors.white,
    borderRadius: 999,
    paddingHorizontal: 18,
  },
  heroBtnPrimaryText: {
    color: colors.green,
    fontSize: 14,
    fontFamily: fonts.semiBold,
  },
  heroBtnSecondary: {
    height: 40,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(255,255,255,0.15)",
    borderRadius: 999,
    paddingHorizontal: 18,
  },
  heroBtnSecondaryText: {
    color: colors.white,
    fontSize: 14,
    fontFamily: fonts.semiBold,
  },
  heroDecorationIcon: {
    marginRight: 10,
    opacity: 0.85,
  },
  statsGridDesktop: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  statsGridMobile: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  statCardDesktop: {
    width: "32.3%",
    minWidth: 220,
    flexGrow: 1,
    backgroundColor: colors.white,
    borderRadius: 20,
    borderWidth: 0.8,
    borderColor: "rgba(11,26,23,0.08)",
    padding: 18,
    gap: 10,
  },
  statCardHeaderDesktop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  statIconWrapDesktop: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  trendPillDesktop: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: colors.greenLight,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  trendPillTextDesktop: {
    fontSize: 12,
    fontFamily: fonts.semiBold,
    color: colors.green,
  },
  statValueDesktop: {
    fontSize: 24,
    fontFamily: fonts.extraBold,
    color: colors.ink,
    marginTop: 4,
  },
  statLabelDesktop: {
    fontSize: 14,
    fontFamily: fonts.regular,
    color: colors.muted,
  },
  bottomGrid: {
    flexDirection: "row",
    gap: 24,
  },
  bottomGridTablet: {
    flexDirection: "column",
  },
  chartCard: {
    flex: 1.5,
    backgroundColor: colors.white,
    borderRadius: 24,
    borderWidth: 0.8,
    borderColor: "rgba(11,26,23,0.08)",
    padding: 24,
  },
  activityCard: {
    flex: 1,
    backgroundColor: colors.white,
    borderRadius: 24,
    borderWidth: 0.8,
    borderColor: "rgba(11,26,23,0.08)",
    padding: 24,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  cardHeaderTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  cardTitle: {
    fontSize: 18,
    fontFamily: fonts.bold,
    color: colors.ink,
  },
  cardSubtext: {
    fontSize: 14,
    fontFamily: fonts.regular,
    color: colors.muted,
  },
  analyticsLink: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  analyticsLinkText: {
    fontSize: 14,
    fontFamily: fonts.semiBold,
    color: colors.green,
  },
  chartSvgWrap: {
    marginTop: 10,
    width: "100%",
  },
  activityList: {
    gap: 12,
    marginTop: 8,
  },
  activityItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 10,
    borderRadius: 14,
    backgroundColor: "#FAFBFB",
  },
  activityIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  activityContent: {
    flex: 1,
    gap: 2,
  },
  activityTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  activityTitle: {
    fontSize: 14,
    fontFamily: fonts.semiBold,
    color: colors.ink,
  },
  unreadOrangeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.orange,
  },
  activityDesc: {
    fontSize: 12,
    fontFamily: fonts.regular,
    color: colors.muted,
  },
  activityTime: {
    fontSize: 11,
    fontFamily: fonts.semiBold,
    color: colors.muted,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
  },
  modalBackdropTouch: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  boostModalCard: {
    width: "100%",
    maxWidth: 520,
    backgroundColor: colors.white,
    borderRadius: 24,
    padding: 24,
    gap: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 10,
  },
  boostModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  boostHeaderIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.greenLight,
    alignItems: "center",
    justifyContent: "center",
  },
  boostModalTitle: {
    fontSize: 18,
    fontFamily: fonts.headingBold,
    fontWeight: "700",
    color: colors.ink,
  },
  boostModalSub: {
    fontSize: 13,
    color: colors.muted,
    fontFamily: fonts.regular,
    marginTop: 2,
  },
  modalCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#F4F6F5",
    alignItems: "center",
    justifyContent: "center",
  },
  packagesList: {
    gap: 12,
  },
  pkgCard: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    padding: 14,
    borderRadius: 16,
    borderWidth: 1.2,
    borderColor: "rgba(11, 26, 23, 0.08)",
    backgroundColor: colors.white,
  },
  pkgCardSelected: {
    borderColor: colors.green,
    backgroundColor: "#F4F9F7",
  },
  pkgRadio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: "#767676",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
  },
  pkgRadioSelected: {
    backgroundColor: colors.green,
    borderColor: colors.green,
  },
  pkgTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  pkgName: {
    fontSize: 15,
    fontFamily: fonts.semiBold,
    fontWeight: "600",
    color: colors.ink,
  },
  pkgBadge: {
    backgroundColor: colors.greenLight,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
  },
  pkgBadgeText: {
    fontSize: 11,
    fontFamily: fonts.bold,
    color: colors.green,
  },
  pkgDesc: {
    fontSize: 13,
    fontFamily: fonts.regular,
    color: colors.muted,
    lineHeight: 18,
  },
  pkgPrice: {
    fontSize: 13,
    fontFamily: fonts.semiBold,
    color: colors.green,
    marginTop: 4,
  },
  boostModalActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginTop: 4,
  },
  boostCancelBtn: {
    flex: 1,
    height: 44,
    borderRadius: 999,
    borderWidth: 1.2,
    borderColor: "rgba(11, 26, 23, 0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  boostCancelBtnText: {
    fontSize: 14,
    fontFamily: fonts.semiBold,
    color: colors.muted,
  },
  boostConfirmBtn: {
    flex: 2,
    height: 44,
    borderRadius: 999,
    backgroundColor: colors.green,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    shadowColor: colors.green,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  boostConfirmBtnText: {
    fontSize: 14,
    fontFamily: fonts.semiBold,
    color: colorTokens.onBrand,
  },
  tabHeroBanner: {
    padding: 22,
    borderRadius: 20,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "rgba(11, 26, 23, 0.08)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    marginBottom: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 1,
  },
  tabHeroBannerPhone: {
    flexDirection: "column",
    alignItems: "stretch",
    padding: 16,
    borderRadius: 18,
    gap: 14,
  },
  tabHeroHeader: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  tabHeroHeaderPhone: {
    flex: 0,
    alignItems: "flex-start",
    gap: 12,
  },
  tabHeroTextWrap: {
    flex: 1,
    gap: 4,
  },
  tabHeroIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: colors.greenLight,
    alignItems: "center",
    justifyContent: "center",
  },
  tabHeroTitle: {
    fontSize: 20,
    fontFamily: fonts.extraBold,
    color: colors.ink,
    letterSpacing: -0.3,
  },
  tabHeroTitlePhone: {
    fontSize: 18,
    lineHeight: 24,
  },
  tabHeroSubtitle: {
    fontSize: 13.5,
    fontFamily: fonts.regular,
    color: colors.muted,
    lineHeight: 20,
    maxWidth: 680,
  },
  tabHeroSubtitlePhone: {
    fontSize: 12.5,
    lineHeight: 18,
  },
  tabHeroActionBtn: {
    height: 40,
    paddingHorizontal: 18,
    borderRadius: 999,
    backgroundColor: colors.green,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    shadowColor: colors.green,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  tabHeroActionBtnPhone: {
    alignSelf: "flex-start",
  },
  tabHeroActionText: {
    fontSize: 13,
    fontFamily: fonts.bold,
    color: colors.ink,
  },
  kpiRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  kpiCard: {
    flex: 1,
    minWidth: 150,
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(11, 26, 23, 0.08)",
  },
  kpiCardPhone: {
    minWidth: "46%",
    padding: 14,
  },
  kpiValue: {
    fontSize: 22,
    fontFamily: fonts.extraBold,
  },
  kpiLabel: {
    fontSize: 13,
    fontFamily: fonts.semiBold,
    color: colors.ink,
    marginTop: 4,
  },
  kpiSub: {
    fontSize: 11,
    fontFamily: fonts.regular,
    color: colors.muted,
    marginTop: 2,
  },
  boostBenchmarkRow: {
    gap: 8,
  },
  boostBenchmarkItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  boostBenchmarkText: {
    flex: 1,
    fontSize: 12,
    fontFamily: fonts.regular,
    color: colors.muted,
  },
  boostBenchmarkValue: {
    fontFamily: fonts.bold,
    color: colors.ink,
  },
  tabCard: {
    backgroundColor: colors.white,
    borderRadius: 20,
    padding: 22,
    borderWidth: 1,
    borderColor: "rgba(11, 26, 23, 0.08)",
  },
  tabCardPhone: {
    padding: 16,
    borderRadius: 16,
  },
  tabCardHeader: {
    marginBottom: 16,
  },
  tabCardTitle: {
    fontSize: 17,
    fontFamily: fonts.bold,
    color: colors.ink,
  },
  tabCardSub: {
    fontSize: 13,
    fontFamily: fonts.regular,
    color: colors.muted,
    marginTop: 2,
  },
  boostPackagesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
  },
  boostPkgCard: {
    flex: 1,
    minWidth: 250,
    backgroundColor: "#F9FAF9",
    borderRadius: 16,
    padding: 20,
    borderWidth: 1.2,
    borderColor: "rgba(11, 26, 23, 0.08)",
    justifyContent: "space-between",
  },
  boostPkgCardPopular: {
    backgroundColor: colors.white,
    borderColor: colors.green,
    shadowColor: colors.green,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 3,
  },
  popularTag: {
    alignSelf: "flex-start",
    backgroundColor: colors.green,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 3,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginBottom: 10,
  },
  popularTagText: {
    fontSize: 11,
    fontFamily: fonts.bold,
    color: colors.ink,
  },
  standardTag: {
    alignSelf: "flex-start",
    backgroundColor: colors.blueLight,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 3,
    marginBottom: 10,
  },
  standardTagText: {
    fontSize: 11,
    fontFamily: fonts.semiBold,
    color: colors.blue,
  },
  boostPkgName: {
    fontSize: 16,
    fontFamily: fonts.bold,
    color: colors.ink,
  },
  boostPkgPrice: {
    fontSize: 14,
    fontFamily: fonts.semiBold,
    color: colors.green,
    marginTop: 4,
    marginBottom: 14,
  },
  pkgBulletsList: {
    gap: 8,
    marginBottom: 18,
  },
  pkgBulletRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  pkgBulletText: {
    fontSize: 12.5,
    fontFamily: fonts.regular,
    color: colors.muted,
    flex: 1,
  },
  selectPkgBtn: {
    height: 40,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.green,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  selectPkgBtnPopular: {
    backgroundColor: colors.green,
  },
  selectPkgBtnText: {
    fontSize: 13,
    fontFamily: fonts.bold,
    color: colors.green,
  },
  selectPkgBtnTextPopular: {
    color: colors.ink,
  },
  emptyStateContainer: {
    alignItems: "center",
    paddingVertical: 32,
    paddingHorizontal: 16,
    gap: 8,
  },
  emptyIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.greenLight,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 6,
  },
  emptyTitle: {
    fontSize: 16,
    fontFamily: fonts.bold,
    color: colors.ink,
  },
  emptyDesc: {
    fontSize: 13,
    fontFamily: fonts.regular,
    color: colors.muted,
    textAlign: "center",
    maxWidth: 420,
    lineHeight: 19,
  },
  emptyActionBtn: {
    marginTop: 8,
    backgroundColor: colors.green,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 999,
  },
  emptyActionBtnText: {
    fontSize: 13,
    fontFamily: fonts.bold,
    color: colors.ink,
  },
  insightsCardsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
  },
  insightCard: {
    flex: 1,
    minWidth: 250,
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 18,
    borderWidth: 1,
    borderColor: "rgba(11, 26, 23, 0.08)",
    gap: 8,
  },
  insightCardIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },
  insightCardTitle: {
    fontSize: 15,
    fontFamily: fonts.bold,
    color: colors.ink,
  },
  insightCardDesc: {
    fontSize: 13,
    fontFamily: fonts.regular,
    color: colors.muted,
    lineHeight: 18,
  },
  insightPill: {
    alignSelf: "flex-start",
    backgroundColor: colors.greenLight,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    marginTop: 4,
  },
  insightPillText: {
    fontSize: 11,
    fontFamily: fonts.semiBold,
    color: colors.green,
  },
  tableContainer: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(11, 26, 23, 0.08)",
    overflow: "hidden",
  },
  tableHeaderRow: {
    flexDirection: "row",
    backgroundColor: "#F4F6F5",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  tableColHeader: {
    fontSize: 12,
    fontFamily: fonts.bold,
    color: colors.muted,
    textTransform: "uppercase",
  },
  tableRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: "rgba(11, 26, 23, 0.06)",
    backgroundColor: colors.white,
  },
  tableRowEven: {
    backgroundColor: "#FBFDFB",
  },
  tableCellTextBold: {
    fontSize: 13.5,
    fontFamily: fonts.bold,
    color: colors.ink,
  },
  tableCellText: {
    fontSize: 13,
    fontFamily: fonts.regular,
    color: colors.ink,
  },
  demandBadge: {
    alignSelf: "flex-start",
    backgroundColor: colors.greenLight,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
  },
  demandBadgeText: {
    fontSize: 11,
    fontFamily: fonts.semiBold,
    color: colors.green,
  },
  payoutMethodsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
  },
  payoutMethodCard: {
    flex: 1,
    minWidth: 250,
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 18,
    borderWidth: 1,
    borderColor: "rgba(11, 26, 23, 0.08)",
    gap: 6,
  },
  payoutCardTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  payoutMethodName: {
    fontSize: 15,
    fontFamily: fonts.bold,
    color: colors.ink,
  },
  availableBadge: {
    backgroundColor: "#F4F6F5",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
  },
  availableBadgeText: {
    fontSize: 11,
    fontFamily: fonts.semiBold,
    color: colors.muted,
  },
  connectPayoutBtn: {
    alignSelf: "flex-start",
    marginTop: 4,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: radius.pill,
    backgroundColor: colors.greenLight,
  },
  connectPayoutBtnText: {
    fontSize: 12,
    fontFamily: fonts.bold,
    color: colors.green,
  },
  payoutAccountNo: {
    fontSize: 13,
    fontFamily: fonts.semiBold,
    color: colors.ink,
  },
  payoutSchedule: {
    fontSize: 12,
    fontFamily: fonts.regular,
    color: colors.muted,
  },
  supportChannelsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
  },
  supportChannelCard: {
    flex: 1,
    minWidth: 230,
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 18,
    borderWidth: 1,
    borderColor: "rgba(11, 26, 23, 0.08)",
    gap: 4,
  },
  supportChannelIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 6,
  },
  supportChannelTitle: {
    fontSize: 14,
    fontFamily: fonts.bold,
    color: colors.ink,
  },
  supportChannelValue: {
    fontSize: 13.5,
    fontFamily: fonts.semiBold,
    color: colors.green,
  },
  supportChannelSub: {
    fontSize: 12,
    fontFamily: fonts.regular,
    color: colors.muted,
  },
  faqList: {
    gap: 14,
  },
  faqItem: {
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(11, 26, 23, 0.06)",
    gap: 4,
  },
  faqQuestion: {
    fontSize: 14.5,
    fontFamily: fonts.bold,
    color: colors.ink,
  },
  faqAnswer: {
    fontSize: 13,
    fontFamily: fonts.regular,
    color: colors.muted,
    lineHeight: 19,
  },
});
