import { Platform, StyleSheet } from "react-native";
import { colorTokens, colors, fonts, layout, shadow } from "@/theme";

export const styles = StyleSheet.create({
  shell: {
    width: "100%",
    flex: 1,
    backgroundColor: "#F8FAF9",
  },
  sidebar: {
    width: 256,
    paddingLeft: 16,
    paddingRight: 16.8,
    paddingVertical: 24,
    backgroundColor: "#FFFFFF",
    borderRightWidth: 1.8,
    borderRightColor: "rgba(11, 26, 23, 0.05)",
  },
  sidebarModal: {
    width: 260,
    borderRightWidth: 0,
    ...shadow,
  },
  sidebarTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 8,
    paddingBottom: 24,
  },
  circleButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F8FAF9",
  },
  sideNav: {
    gap: 4,
    width: "100%",
  },
  sideLink: {
    width: "100%",
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderRadius: 16,
  },
  sideLinkActive: {
    backgroundColor: "#E6FAF4",
  },
  sideLinkText: {
    color: "#5C6B66",
    fontFamily: fonts.semiBold,
    fontSize: 14,
    fontWeight: "600",
  },
  sideLinkTextActive: {
    color: colors.greenOnLight,
    fontFamily: fonts.semiBold,
    fontWeight: "600",
  },
  badge: {
    marginLeft: "auto",
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#F4823A",
    alignItems: "center",
    justifyContent: "center",
  },
  badgeText: {
    color: colorTokens.onAccent,
    fontFamily: fonts.semiBold,
    fontSize: 12,
    fontWeight: "600",
  },
  sidebarSpacer: {
    flex: 1,
    minHeight: 30,
  },
  sidebarCard: {
    padding: 16,
    backgroundColor: "#E6FAF4",
    borderRadius: 16,
    alignItems: "center",
    gap: 8,
  },
  sidebarCardIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#04cf92",
    alignItems: "center",
    justifyContent: "center",
  },
  sidebarCardTitle: {
    color: "#0B1A17",
    fontFamily: fonts.semiBold,
    fontSize: 15,
    fontWeight: "600",
    textAlign: "center",
  },
  sidebarCardSubtitle: {
    color: "#5C6B66",
    fontFamily: fonts.regular,
    fontSize: 12,
    lineHeight: 16,
    textAlign: "center",
  },
  postAdButton: {
    width: "100%",
    height: 38.4,
    backgroundColor: "#04cf92",
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 4,
  },
  postAdButtonText: {
    color: colorTokens.onBrand,
    fontFamily: fonts.semiBold,
    fontSize: 14,
    fontWeight: "600",
  },

  pageColumn: {
    width: "100%",
    flex: 1,
    backgroundColor: "#F8FAF9",
  },
  pageColumnMobile: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    width: "100%",
  },
  topbarSafe: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 50,
    backgroundColor: "rgba(255, 255, 255, 0.76)",
    borderBottomWidth: 0,
    width: "100%",
    ...(Platform.select({
      web: {
        position: "fixed",
        top: 0,
        left: 0,
        right: 0,
        backdropFilter: "blur(16px) saturate(180%)",
        WebkitBackdropFilter: "blur(16px) saturate(180%)",
        boxShadow: "0 4px 20px -2px rgba(11, 26, 23, 0.05)",
        transition: "background-color 0.3s ease, backdrop-filter 0.3s ease, box-shadow 0.3s ease",
      },
      default: {
        shadowColor: "#0B1A17",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.03,
        shadowRadius: 10,
        elevation: 2,
      },
    }) as any),
  },
  topbarSafeCrystal: {
    backgroundColor: "transparent",
    borderBottomWidth: 0,
    borderBottomColor: "transparent",
    ...(Platform.select({
      web: {
        backdropFilter: "none",
        WebkitBackdropFilter: "none",
        boxShadow: "none",
      },
      default: {
        elevation: 0,
        shadowOpacity: 0,
      },
    }) as any),
  },
  topNavLinkTextCrystal: {
    color: "#FFFFFF",
    ...(Platform.select({
      web: {
        textShadow: "0 1px 4px rgba(0, 0, 0, 0.45)",
      },
      default: {},
    }) as any),
  },
  rightmoveSignInBtnCrystal: {
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    borderColor: "rgba(255, 255, 255, 0.4)",
    ...(Platform.select({
      web: {
        backdropFilter: "blur(4px)",
        WebkitBackdropFilter: "blur(4px)",
      },
      default: {},
    }) as any),
  },
  rightmoveSignInTextCrystal: {
    color: "#FFFFFF",
  },
  topbar: {
    width: "100%",
    maxWidth: layout.containerMaxWidth,
    marginHorizontal: "auto",
    minHeight: layout.navHeight,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: layout.gutter,
    paddingVertical: 12,
    gap: 16,
  },
  topbarTablet: {
    minHeight: layout.navHeightTablet,
    paddingHorizontal: layout.gutterTablet,
  },
  topbarPhone: {
    minHeight: layout.navHeightPhone,
    paddingHorizontal: layout.gutterPhone,
    gap: 4,
  },
  topbarLeft: {
    flexShrink: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 12,
  },
  topbarLeftPhone: {
    gap: 6,
  },
  topNavCenter: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 20,
    minWidth: 0,
    paddingHorizontal: 8,
  },
  topNavLink: {
    position: "relative",
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 8,
    flexShrink: 0,
    ...(Platform.select({
      web: { transition: "background-color 0.15s ease" },
      default: {},
    }) as any),
  },
  topNavLinkHovered: {
    backgroundColor: "rgba(11, 26, 23, 0.04)",
  },
  topNavLinkText: {
    fontFamily: fonts.semiBold,
    fontSize: 15,
    fontWeight: "600",
    color: "#0B1A17",
    letterSpacing: -0.2,
    ...(Platform.select({
      web: { whiteSpace: "nowrap" },
      default: {},
    }) as any),
  },
  topNavLinkTextActive: {
    color: "#04cf92",
    fontWeight: "700",
  },
  topNavIndicator: {
    position: "absolute",
    bottom: 0,
    left: 4,
    right: 4,
    height: 2.5,
    borderRadius: 999,
    backgroundColor: "#04cf92",
  },
  mobileBrandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  menuButton: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
    backgroundColor: "#F8FAF9",
    borderWidth: 0.8,
    borderColor: "rgba(11, 26, 23, 0.08)",
  },
  menuButtonPhone: {
    width: 32,
    height: 32,
    borderRadius: 16,
  },
  menuButtonCrystal: {
    backgroundColor: "rgba(255, 255, 255, 0.16)",
    borderColor: "rgba(255, 255, 255, 0.32)",
    borderWidth: 1,
    ...(Platform.select({
      web: {
        backdropFilter: "blur(10px)",
        WebkitBackdropFilter: "blur(10px)",
      },
      default: {},
    }) as any),
  },
  actionsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  authPill: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "#F8FAF9",
    borderWidth: 0.8,
    borderColor: "rgba(11, 26, 23, 0.08)",
  },
  authPillPhone: {
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  authPillText: {
    color: "#5C6B66",
    fontFamily: fonts.semiBold,
    fontSize: 13,
    fontWeight: "600",
    maxWidth: 120,
  },
  authPillTextPhone: {
    fontSize: 11,
    maxWidth: 80,
  },
  notificationButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F8FAF9",
    borderWidth: 0.8,
    borderColor: "rgba(11, 26, 23, 0.08)",
  },
  notificationButtonPhone: {
    width: 32,
    height: 32,
    borderRadius: 16,
  },
  notificationButtonCrystal: {
    backgroundColor: "rgba(255, 255, 255, 0.16)",
    borderColor: "rgba(255, 255, 255, 0.32)",
    borderWidth: 1,
    ...(Platform.select({
      web: {
        backdropFilter: "blur(10px)",
        WebkitBackdropFilter: "blur(10px)",
      },
      default: {},
    }) as any),
  },
  // Red with white text (5.25:1). The theme's orange "notification" token is
  // 2.59:1 on white, too low for a number people need to read.
  notificationBadge: {
    position: "absolute",
    top: -3,
    right: -3,
    minWidth: 17,
    height: 17,
    paddingHorizontal: 4,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colorTokens.errorText,
    borderWidth: 1.5,
    borderColor: colorTokens.surface,
  },
  notificationBadgeText: {
    color: colorTokens.onDanger,
    fontFamily: fonts.bold,
    fontSize: 10,
    fontWeight: "700",
    lineHeight: 12,
  },
  topRightActions: {
    flexShrink: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 12,
    marginLeft: "auto",
  },
  topRightActionsPhone: {
    gap: 6,
    marginLeft: "auto",
  },
  listPropertyBtn: {
    flexShrink: 0,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
    borderRadius: 8,
    backgroundColor: "#04cf92",
  },
  listPropertyText: {
    color: colorTokens.onBrand,
    fontFamily: fonts.semiBold,
    fontSize: 14,
    fontWeight: "700",
    ...(Platform.select({
      web: { whiteSpace: "nowrap" },
      default: {},
    }) as any),
  },
  rightmoveSignInBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    backgroundColor: "rgba(255, 255, 255, 0.85)",
    borderWidth: 1.5,
    borderColor: "rgba(4, 207, 146, 0.8)",
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 8,
    height: 38,
    flexShrink: 0,
    ...(Platform.select({
      web: {
        backdropFilter: "blur(8px)",
        WebkitBackdropFilter: "blur(8px)",
      },
      default: {},
    }) as any),
  },
  rightmoveSignInBtnPhone: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    height: 32,
    gap: 4,
    borderRadius: 6,
    borderWidth: 1.5,
  },
  rightmoveSignInText: {
    color: "#0B1A17",
    fontFamily: fonts.semiBold,
    fontSize: 14,
    fontWeight: "700",
    ...(Platform.select({
      web: { whiteSpace: "nowrap" },
      default: {},
    }) as any),
  },
  rightmoveSignInTextPhone: {
    fontSize: 12.5,
  },
  userDropdownWrap: {
    position: "relative",
    zIndex: 60,
  },
  guestDropdownWrap: {
    position: "relative",
    zIndex: 60,
  },
  guestPillGroup: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderColor: "#04cf92",
    borderWidth: 1.5,
    borderRadius: 8,
    height: 38,
    overflow: "hidden",
  },
  guestPillGroupPhone: {
    height: 32,
    borderRadius: 6,
  },
  guestSignInBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    paddingHorizontal: 12,
    height: "100%",
  },
  guestSignInBtnPhone: {
    paddingHorizontal: 8,
    gap: 4,
  },
  guestPillDivider: {
    width: 1,
    height: 20,
    backgroundColor: "rgba(4, 207, 146, 0.3)",
  },
  guestTriangleBtn: {
    height: "100%",
    paddingHorizontal: 9,
    justifyContent: "center",
    alignItems: "center",
  },
  guestTriangleBtnPhone: {
    paddingHorizontal: 6,
  },
  guestTriangleBtnActive: {
    backgroundColor: "rgba(4, 207, 146, 0.12)",
  },
  userDropdownTrigger: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    paddingVertical: 3,
    paddingLeft: 3,
    paddingRight: 9,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(11, 26, 23, 0.10)",
    backgroundColor: "#FFFFFF",
  },
  userDropdownTriggerCrystal: {
    backgroundColor: "rgba(255, 255, 255, 0.16)",
    borderColor: "rgba(255, 255, 255, 0.32)",
    borderWidth: 1,
    ...(Platform.select({
      web: {
        backdropFilter: "blur(10px)",
        WebkitBackdropFilter: "blur(10px)",
      },
      default: {},
    }) as any),
  },
  userDropdownTriggerActive: {
    borderColor: "#04cf92",
    backgroundColor: "rgba(4, 207, 146, 0.04)",
  },
  triangleIconBox: {
    width: 12,
    height: 12,
    justifyContent: "center",
    alignItems: "center",
  },
  triangleIconBoxOpen: {
    transform: [{ rotate: "180deg" }],
  },
  dropdownBackdrop: {
    position: (Platform.OS === "web" ? "fixed" : "absolute") as any,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 80,
  },
  userDropdownMenu: {
    position: "absolute",
    top: 48,
    right: 0,
    width: 240,
    backgroundColor: "rgba(255, 255, 255, 0.92)",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(11, 26, 23, 0.08)",
    padding: 6,
    zIndex: 90,
    ...Platform.select({
      web: {
        backdropFilter: "blur(16px)",
        WebkitBackdropFilter: "blur(16px)",
        boxShadow: "0 16px 36px -4px rgba(11, 26, 23, 0.12), 0 2px 8px -2px rgba(11, 26, 23, 0.04), 0 0 0 1px rgba(11, 26, 23, 0.04)",
      } as any,
      default: {
        shadowColor: "#0B1A17",
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.12,
        shadowRadius: 18,
        elevation: 10,
      },
    }),
  },
  userDropdownMenuPhone: {
    width: 220,
  },
  userDropdownProfile: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  dropdownAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(11, 26, 23, 0.08)",
  },
  dropdownProfileInfo: {
    flex: 1,
    justifyContent: "center",
  },
  userDropdownName: {
    fontFamily: fonts.semiBold,
    fontSize: 14,
    fontWeight: "600",
    color: "#0B1A17",
    letterSpacing: -0.2,
  },
  userDropdownEmail: {
    fontFamily: fonts.regular,
    fontSize: 12,
    color: "#707E78",
    marginTop: 1,
  },
  guestMenuHeader: {
    paddingHorizontal: 10,
    paddingTop: 8,
    paddingBottom: 4,
  },
  guestMenuTitle: {
    fontFamily: fonts.semiBold,
    fontSize: 11,
    fontWeight: "700",
    color: "#8A9993",
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  dropdownDivider: {
    height: 1,
    backgroundColor: "rgba(11, 26, 23, 0.06)",
    marginVertical: 4,
    marginHorizontal: 4,
  },
  dropdownItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 8,
    paddingHorizontal: 8,
    borderRadius: 8,
  },
  dropdownItemPressed: {
    backgroundColor: "rgba(11, 26, 23, 0.05)",
  },
  dropdownIconBox: {
    width: 30,
    height: 30,
    borderRadius: 7,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(11, 26, 23, 0.04)",
  },
  dropdownItemText: {
    fontFamily: fonts.medium,
    fontSize: 14,
    fontWeight: "500",
    color: "#0B1A17",
  },
  locationPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "#FFFFFF",
    borderWidth: 1.8,
    borderColor: "rgba(11, 26, 23, 0.08)",
  },
  locationPillPhone: {
    paddingHorizontal: 7,
    paddingVertical: 5,
    gap: 3,
    borderWidth: 1.2,
  },
  locationPillText: {
    color: "#0B1A17",
    fontFamily: fonts.semiBold,
    fontSize: 14,
    fontWeight: "600",
  },
  locationPillTextPhone: {
    fontSize: 11.5,
    maxWidth: 52,
  },
  logInPill: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "#FFFFFF",
    borderWidth: 1.8,
    borderColor: "rgba(11, 26, 23, 0.08)",
  },
  logInPillText: {
    color: "#0B1A17",
    fontFamily: fonts.semiBold,
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 20,
    textAlign: "center",
  },
  notificationWrap: {
    position: "relative",
  },
  iconCircleButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
    borderWidth: 0.8,
    borderColor: "rgba(11, 26, 23, 0.08)",
  },
  iconCircleButtonPhone: {
    width: 32,
    height: 32,
    borderRadius: 16,
  },
  orangeDot: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#F4823A",
  },
  notificationPopover: {
    position: "absolute",
    top: 48,
    right: 0,
    width: 320,
    padding: 14,
    borderRadius: 14,
    backgroundColor: "rgba(255, 255, 255, 0.92)",
    borderWidth: 0.8,
    borderColor: "rgba(11, 26, 23, 0.08)",
    zIndex: 90,
    ...shadow,
    ...(Platform.select({
      web: {
        backdropFilter: "blur(16px)",
        WebkitBackdropFilter: "blur(16px)",
      },
      default: {},
    }) as any),
  },
  notificationTitle: {
    color: "#0B1A17",
    fontFamily: fonts.semiBold,
    fontSize: 13,
    fontWeight: "600",
  },
  notificationCopy: {
    marginTop: 4,
    color: "#5C6B66",
    fontFamily: fonts.regular,
    fontSize: 12,
    lineHeight: 16,
  },
  avatarButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    overflow: "hidden",
  },
  avatarButtonPhone: {
    width: 28,
    height: 28,
    borderRadius: 14,
  },
  avatarImage: {
    width: "100%",
    height: "100%",
  },
  avatarImagePhone: {
    width: 28,
    height: 28,
    borderRadius: 14,
  },

  pageScrollContent: {
    flexGrow: 1,
    width: "100%",
    alignItems: "center",
    backgroundColor: "#F8FAF9",
  },

  bleed: {
    width: "100%",
  },

  // Same container as the navbar — alignment is structural, not tuned.
  mainGutter: {
    width: "100%",
    maxWidth: layout.containerMaxWidth,
    paddingTop: 16,
    paddingBottom: 48,
  },
  // `fluid` pages (guides) run edge to edge instead of in the container.
  mainGutterFluid: {
    width: "100%",
    maxWidth: "100%",
    paddingTop: 16,
    paddingBottom: 48,
  },
  mainGutterPhone: {
    paddingTop: 10,
    paddingBottom: 24,
  },

  main: {
    width: "100%",
    paddingHorizontal: layout.gutter,
  },
  mainFluid: {
    width: "100%",
    paddingHorizontal: 0,
  },
  mainPhone: {
    paddingHorizontal: layout.gutterPhone,
  },

  /* Mobile bottom bar */
  mobileNavSafe: {
    width: "100%",
    backgroundColor: "#FFFFFF",
    borderTopWidth: 0.8,
    borderTopColor: "rgba(11, 26, 23, 0.08)",
    ...shadow,
  },
  mobileNav: {
    minHeight: 60,
    flexDirection: "row",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  mobileNavLink: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
  },
  mobileNavText: {
    color: "#7B8983",
    fontFamily: fonts.semiBold,
    fontSize: 10,
  },
  mobileNavTextActive: {
    color: colors.greenOnLight,
    fontFamily: fonts.semiBold,
  },
  drawerLayer: {
    flex: 1,
    flexDirection: "row",
  },
  drawerOverlay: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: "rgba(11, 26, 23, 0.4)",
  },
});
