import { Platform, StyleSheet } from "react-native";
import { colorTokens, colors, fonts } from "@/theme";

export const styles = StyleSheet.create({
  outerContainer: {
    width: "100%",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 36,
    paddingBottom: 24,
    backgroundColor: "#FFFFFF",
  },
  maxWidthWrapper: {
    width: "100%",
    maxWidth: 1200,
  },
  cleanCard: {
    position: "relative",
    backgroundColor: "#F8FAF9",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(11, 26, 23, 0.08)",
    paddingHorizontal: 40,
    paddingVertical: 36,
    overflow: "hidden",
    ...(Platform.select({
      web: {
        boxShadow: "0 10px 30px rgba(11, 26, 23, 0.03)",
      },
      default: {
        shadowColor: "#0B1A17",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.04,
        shadowRadius: 14,
        elevation: 2,
      },
    }) as any),
  },
  cleanCardPhone: {
    paddingHorizontal: 20,
    paddingVertical: 24,
    borderRadius: 20,
  },
  cardLayout: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 40,
  },
  cardLayoutStacked: {
    flexDirection: "column",
    alignItems: "stretch",
    gap: 28,
  },
  mainCopyWrap: {
    flex: 1.25,
    maxWidth: 680,
  },
  mainCopyWrapPhone: {
    maxWidth: "100%",
  },
  eyebrowContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  eyebrowBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 100,
    backgroundColor: "#E6FAF4",
    borderWidth: 1,
    borderColor: "rgba(4, 207, 146, 0.25)",
  },
  eyebrowText: {
    color: "#0B1A17",
    fontFamily: fonts.semiBold,
    fontSize: 12,
    letterSpacing: 0.3,
    textTransform: "uppercase",
  },
  headline: {
    color: "#0B1A17",
    fontFamily: fonts.bold,
    fontSize: 36,
    lineHeight: 42,
    letterSpacing: -0.6,
    marginBottom: 12,
  },
  headlinePhone: {
    fontSize: 27,
    lineHeight: 33,
    letterSpacing: -0.4,
  },
  subcopy: {
    color: "#5C6B66",
    fontFamily: fonts.regular,
    fontSize: 15,
    lineHeight: 24,
    marginBottom: 24,
  },
  subcopyPhone: {
    fontSize: 14,
    lineHeight: 22,
    marginBottom: 20,
  },
  ctaRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 24,
  },
  ctaRowPhone: {
    flexDirection: "column",
    alignItems: "stretch",
    gap: 10,
    marginBottom: 18,
  },
  fullWidthButton: {
    width: "100%",
    justifyContent: "center",
  },
  buttonPressed: {
    opacity: 0.88,
    transform: [{ scale: 0.985 }],
  },
  trustPillsRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 12,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "rgba(11, 26, 23, 0.06)",
  },
  trustPillsPhoneWrap: {
    paddingTop: 16,
    paddingBottom: 8,
    marginBottom: 6,
    borderTopWidth: 1,
    borderTopColor: "rgba(11, 26, 23, 0.06)",
    gap: 10,
  },
  trustPillsTopRowPhone: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    flexWrap: "nowrap",
    gap: 8,
  },
  trustPillCenterPhone: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  trustPillItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  trustPillText: {
    color: "#5C6B66",
    fontFamily: fonts.medium,
    fontSize: 12,
  },
  trustDot: {
    width: 3,
    height: 3,
    borderRadius: 2,
    backgroundColor: "rgba(11, 26, 23, 0.2)",
  },
  visualSideWrap: {
    flex: 0.8,
    minWidth: 280,
  },
  visualSideWrapPhone: {
    minWidth: "100%",
  },
  aestheticPlaque: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 24,
    borderWidth: 1,
    borderColor: "rgba(11, 26, 23, 0.08)",
    ...(Platform.select({
      web: {
        boxShadow: "0 8px 24px rgba(11, 26, 23, 0.04)",
      },
      default: {},
    }) as any),
  },
  plaqueHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 20,
  },
  plaqueIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: "#E6FAF4",
    alignItems: "center",
    justifyContent: "center",
  },
  plaqueTitle: {
    color: "#0B1A17",
    fontFamily: fonts.semiBold,
    fontSize: 15,
  },
  plaqueSubtitle: {
    color: "#5C6B66",
    fontFamily: fonts.regular,
    fontSize: 12,
    marginTop: 2,
  },
  plaqueStatsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#F8FAF9",
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "rgba(11, 26, 23, 0.05)",
  },
  plaqueStatItem: {
    alignItems: "center",
    flex: 1,
  },
  plaqueStatNum: {
    color: "#0B1A17",
    fontFamily: fonts.bold,
    fontSize: 14,
  },
  plaqueStatLabel: {
    color: "#5C6B66",
    fontFamily: fonts.regular,
    fontSize: 10,
    marginTop: 2,
  },
  plaqueDivider: {
    width: 1,
    height: 24,
    backgroundColor: "rgba(11, 26, 23, 0.08)",
  },
  plaqueActionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: 4,
  },
  plaqueActionText: {
    color: "#04cf92",
    fontFamily: fonts.semiBold,
    fontSize: 13,
  },

  // ─── Modal Styles ──────────────────────────────────────────────
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(11, 26, 23, 0.55)",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
  },
  modalCard: {
    width: "100%",
    maxWidth: 680,
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 28,
    maxHeight: "90%",
    ...(Platform.select({
      web: {
        boxShadow: "0 20px 50px rgba(0, 0, 0, 0.2)",
      },
      default: {
        elevation: 8,
      },
    }) as any),
  },
  modalCardPhone: {
    padding: 18,
    borderRadius: 20,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 18,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(11, 26, 23, 0.06)",
  },
  modalEyebrowRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 4,
  },
  modalEyebrow: {
    color: "#04cf92",
    fontFamily: fonts.semiBold,
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  modalTitle: {
    color: "#0B1A17",
    fontFamily: fonts.bold,
    fontSize: 22,
    lineHeight: 28,
  },
  modalSubtitle: {
    color: "#5C6B66",
    fontFamily: fonts.regular,
    fontSize: 13,
    marginTop: 4,
  },
  modalCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(11, 26, 23, 0.05)",
  },
  modalScrollContent: {
    paddingVertical: 4,
  },
  modalGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  intentCard: {
    flex: 1,
    minWidth: 280,
    flexBasis: "48%",
    backgroundColor: "#F8FAF9",
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "rgba(11, 26, 23, 0.08)",
    padding: 16,
    ...(Platform.select({
      web: {
        transition: "all 0.16s ease",
      },
      default: {},
    }) as any),
  },
  intentCardHovered: {
    borderColor: "rgba(4, 207, 146, 0.4)",
    backgroundColor: "#F3FCF9",
  },
  intentCardSelected: {
    borderColor: "#04cf92",
    backgroundColor: "#E6FAF4",
    ...(Platform.select({
      web: {
        boxShadow: "0 2px 10px rgba(4, 207, 146, 0.15)",
      },
      default: {},
    }) as any),
  },
  intentCardTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  intentCardIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
  },
  intentCardIconWrapSelected: {
    backgroundColor: "rgba(4, 207, 146, 0.15)",
  },
  checkCircleSelected: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#04cf92",
    alignItems: "center",
    justifyContent: "center",
  },
  intentCardContent: {
    gap: 4,
  },
  intentCardTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  intentCardTitle: {
    color: "#0B1A17",
    fontFamily: fonts.semiBold,
    fontSize: 14,
  },
  intentCardTitleSelected: {
    color: "#0B1A17",
    fontFamily: fonts.bold,
  },
  intentBadgePill: {
    backgroundColor: "#FDEEE2",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 8,
  },
  intentBadgeText: {
    color: "#D96A24",
    fontFamily: fonts.semiBold,
    fontSize: 10,
  },
  intentCardDesc: {
    color: "#5C6B66",
    fontFamily: fonts.regular,
    fontSize: 12,
    lineHeight: 16,
  },
  modalFooter: {
    marginTop: 20,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "rgba(11, 26, 23, 0.06)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 12,
  },
  modalFooterHint: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  modalFooterHintText: {
    color: "#5C6B66",
    fontFamily: fonts.medium,
    fontSize: 12,
  },
  modalFooterActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  cancelButton: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 12,
  },
  cancelButtonText: {
    color: "#5C6B66",
    fontFamily: fonts.medium,
    fontSize: 13,
  },
  continueButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#04cf92",
    paddingVertical: 11,
    paddingHorizontal: 20,
    borderRadius: 12,
    ...(Platform.select({
      web: {
        boxShadow: "0 3px 10px rgba(4, 207, 146, 0.3)",
      },
      default: {},
    }) as any),
  },
  continueButtonText: {
    color: colorTokens.onBrand,
    fontFamily: fonts.semiBold,
    fontSize: 14,
  },
  aiEntryCard: {
    marginTop: 4,
    marginBottom: 16,
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: "#04cf92",
    paddingVertical: 13,
    paddingHorizontal: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    ...(Platform.select({
      web: {
        transition: "all 0.16s ease",
        boxShadow: "0 4px 18px rgba(4, 207, 146, 0.10)",
      },
      default: {
        shadowColor: "#04cf92",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 2,
      },
    }) as any),
  },
  aiEntryCardPhone: {
    flexDirection: "column",
    alignItems: "stretch",
    gap: 14,
  },
  aiCardLeft: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  aiCardLeftPhone: {
    alignItems: "flex-start",
  },
  aiIconGlowingWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#E6FAF4",
    borderWidth: 1,
    borderColor: "rgba(4, 207, 146, 0.3)",
    alignItems: "center",
    justifyContent: "center",
  },
  aiTextContainer: {
    flex: 1,
    gap: 3,
  },
  aiHeadlineRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  aiHeadline: {
    fontFamily: fonts.bold,
    fontSize: 15,
    color: colors.ink,
  },
  aiBetaBadge: {
    backgroundColor: "#E6FAF4",
    borderWidth: 1,
    borderColor: "rgba(4, 207, 146, 0.4)",
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 8,
  },
  aiBetaText: {
    fontFamily: fonts.bold,
    fontSize: 9.5,
    color: "#03986A",
    letterSpacing: 0.5,
  },
  aiSubtext: {
    fontFamily: fonts.regular,
    fontSize: 13,
    color: "#5C6B66",
    lineHeight: 18,
  },
  aiCtaButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    backgroundColor: "#04cf92",
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 14,
    ...(Platform.select({
      web: {
        boxShadow: "0 3px 12px rgba(4, 207, 146, 0.35)",
      },
      default: {},
    }) as any),
  },
  aiCtaButtonPhone: {
    width: "100%",
    justifyContent: "center",
    paddingVertical: 12,
  },
  aiCtaButtonText: {
    fontFamily: fonts.semiBold,
    fontSize: 14,
    color: colorTokens.onBrand,
  },
});
